/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Principal.java
 *
 * Created on 15/01/2011, 10:05:14 PM
 */
package registrador;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author jonathan
 */
public class Principal extends javax.swing.JFrame{

    String url_Servidor = "l";
    Libreria obje;

    /** Creates new form Principal */
    public Principal() {
        obje = new Libreria();
        obje.Acceder_Conf();
        obje.cargar_conf();
        url_Servidor = obje.getUrl_Servidor();
        System.out.println(url_Servidor);
        initComponents();
        if (url_Servidor.contains(".mdb")) {
            Menu_Compactar.setEnabled(true);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Menu_Consulta = new javax.swing.JMenuItem();
        Menu_Agrega = new javax.swing.JMenuItem();
        Menu_Modificar = new javax.swing.JMenuItem();
        Menu_Salir = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        Menu_Compactar = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Panel Principal");

        jMenu1.setText("Accciones");

        Menu_Consulta.setText("Consultar y tal vez eliminar");
        Menu_Consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_ConsultaActionPerformed(evt);
            }
        });
        jMenu1.add(Menu_Consulta);

        Menu_Agrega.setText("Agregar usuarios");
        Menu_Agrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_AgregaActionPerformed(evt);
            }
        });
        jMenu1.add(Menu_Agrega);

        Menu_Modificar.setText("Modificar datos de usuarios");
        Menu_Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_ModificarActionPerformed(evt);
            }
        });
        jMenu1.add(Menu_Modificar);

        Menu_Salir.setText("Salir");
        Menu_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_SalirActionPerformed(evt);
            }
        });
        jMenu1.add(Menu_Salir);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Compactar BD");

        Menu_Compactar.setText("Compactar BD");
        Menu_Compactar.setToolTipText("Hace que el archivo acces tenga menor tamaño");
        Menu_Compactar.setEnabled(false);
        Menu_Compactar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_CompactarActionPerformed(evt);
            }
        });
        jMenu3.add(Menu_Compactar);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Acerca de:");

        jMenuItem1.setText("Acerca del programa");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 299, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Menu_ConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_ConsultaActionPerformed
        Consulta obj = new Consulta(url_Servidor, obje);
        obj.show();
    }//GEN-LAST:event_Menu_ConsultaActionPerformed

    private void Menu_AgregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_AgregaActionPerformed
        Agregar obj = new Agregar(url_Servidor, obje);
        obj.show();
    }//GEN-LAST:event_Menu_AgregaActionPerformed

    private void Menu_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Menu_SalirActionPerformed

    private void Menu_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_ModificarActionPerformed
        Modificar obj = new Modificar(url_Servidor, obje);
        obj.show();
    }//GEN-LAST:event_Menu_ModificarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JOptionPane.showMessageDialog(null, "Programa de uso libre", "Registrador_SG 1.0\n By Jonathan", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void Menu_CompactarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_CompactarActionPerformed
        System.out.println("msaccess.exe /compact " + url_Servidor);
        String u = "C:/Program Files/Microsoft Office/Office14/";
        String comando = u + "msaccess.exe /compact " + "\"" + url_Servidor + "\"";

        try {
            Runtime.getRuntime().exec(comando);
        }
        catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_Menu_CompactarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable(){

            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Menu_Agrega;
    private javax.swing.JMenuItem Menu_Compactar;
    private javax.swing.JMenuItem Menu_Consulta;
    private javax.swing.JMenuItem Menu_Modificar;
    private javax.swing.JMenuItem Menu_Salir;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
