/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on 01/05/2010, 07:57:21 PM
 */

package ventana;

import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import javax.swing.JPopupMenu;

/**
 *
 * @author JONATHAN
 */
public class NewJFrame extends javax.swing.JFrame {
private boolean popupInvisible = true; //que representa si el popup es invisible o no
    /** Creates new form NewJFrame */
    public NewJFrame() 
    {

        setLocation(500, 250);
        initComponents();
        popupMenu = new JPopupMenu();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        uno = new javax.swing.JMenuItem();
        dos = new javax.swing.JMenuItem();
        boton = new javax.swing.JButton();

        uno.setText("jMenuItem1");
        jPopupMenu1.add(uno);

        dos.setText("jMenuItem2");
        jPopupMenu1.add(dos);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setState(1);

        boton.setText("jButton1");
        boton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonMouseClicked(evt);
            }
        });
        boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(boton)
                .addContainerGap(287, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(boton)
                .addContainerGap(168, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActionPerformed
        // Agreammos el evento del popup al boton
        //MouseEvent eventoMouse=new MouseEvent(boton, 0, evt.getWhen(), KeyEvent.VK_UNDEFINED, 0,jPanel1.getY()+boton.getY() , 1, true);
        MouseEvent eventoMouse = new MouseEvent(boton, 0, evt.getWhen(), KeyEvent.VK_UNDEFINED, 0, boton.getY()-80, 1, true);
        checkPopup(eventoMouse);
    }//GEN-LAST:event_botonActionPerformed

    private void botonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMouseClicked
            if (evt.getClickCount() == 3) {
      //showStatus ("Se ha producido un triple click");
                System.out.println("aaa");
    } else if (evt.getClickCount() == 2) {
     // showStatus ("Se ha producido un doble click");
        System.out.println("aa");
    }

    }//GEN-LAST:event_botonMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton;
    private javax.swing.JMenuItem dos;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JMenuItem uno;
    // End of variables declaration//GEN-END:variables
    private JPopupMenu popupMenu; //el que representa el popup

    private void checkPopup(MouseEvent e) {
        jPopupMenu1.show(e.getComponent(), e.getX(), e.getY());
    }

}
