/*
 * This file is generated by jOOQ.
*/
package com.palominocia.JooqProject.modelo.tables.daos;


import com.palominocia.JooqProject.modelo.tables.Roles;
import com.palominocia.JooqProject.modelo.tables.records.RolesRecord;

import java.sql.Date;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RolesDao extends DAOImpl<RolesRecord, com.palominocia.JooqProject.modelo.tables.pojos.Roles, Long> {

    /**
     * Create a new RolesDao without any configuration
     */
    public RolesDao() {
        super(Roles.ROLES, com.palominocia.JooqProject.modelo.tables.pojos.Roles.class);
    }

    /**
     * Create a new RolesDao with an attached configuration
     */
    public RolesDao(Configuration configuration) {
        super(Roles.ROLES, com.palominocia.JooqProject.modelo.tables.pojos.Roles.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(com.palominocia.JooqProject.modelo.tables.pojos.Roles object) {
        return object.getIdRol();
    }

    /**
     * Fetch records that have <code>ID_ROL IN (values)</code>
     */
    public List<com.palominocia.JooqProject.modelo.tables.pojos.Roles> fetchByIdRol(Long... values) {
        return fetch(Roles.ROLES.ID_ROL, values);
    }

    /**
     * Fetch a unique record that has <code>ID_ROL = value</code>
     */
    public com.palominocia.JooqProject.modelo.tables.pojos.Roles fetchOneByIdRol(Long value) {
        return fetchOne(Roles.ROLES.ID_ROL, value);
    }

    /**
     * Fetch records that have <code>NOMBRE_ROL IN (values)</code>
     */
    public List<com.palominocia.JooqProject.modelo.tables.pojos.Roles> fetchByNombreRol(String... values) {
        return fetch(Roles.ROLES.NOMBRE_ROL, values);
    }

    /**
     * Fetch records that have <code>MCA_HABILITADO IN (values)</code>
     */
    public List<com.palominocia.JooqProject.modelo.tables.pojos.Roles> fetchByMcaHabilitado(String... values) {
        return fetch(Roles.ROLES.MCA_HABILITADO, values);
    }

    /**
     * Fetch records that have <code>FEC_ACTU IN (values)</code>
     */
    public List<com.palominocia.JooqProject.modelo.tables.pojos.Roles> fetchByFecActu(Date... values) {
        return fetch(Roles.ROLES.FEC_ACTU, values);
    }

    /**
     * Fetch records that have <code>ID_USUARIO_MODIF IN (values)</code>
     */
    public List<com.palominocia.JooqProject.modelo.tables.pojos.Roles> fetchByIdUsuarioModif(String... values) {
        return fetch(Roles.ROLES.ID_USUARIO_MODIF, values);
    }
}
