/*
 * This file is generated by jOOQ.
*/
package com.palominocia.JooqProject.modelo.tables.daos;


import com.palominocia.JooqProject.modelo.tables.RolesUsuario;
import com.palominocia.JooqProject.modelo.tables.records.RolesUsuarioRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RolesUsuarioDao extends DAOImpl<RolesUsuarioRecord, com.palominocia.JooqProject.modelo.tables.pojos.RolesUsuario, Record2<String, Long>> {

    /**
     * Create a new RolesUsuarioDao without any configuration
     */
    public RolesUsuarioDao() {
        super(RolesUsuario.ROLES_USUARIO, com.palominocia.JooqProject.modelo.tables.pojos.RolesUsuario.class);
    }

    /**
     * Create a new RolesUsuarioDao with an attached configuration
     */
    public RolesUsuarioDao(Configuration configuration) {
        super(RolesUsuario.ROLES_USUARIO, com.palominocia.JooqProject.modelo.tables.pojos.RolesUsuario.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Record2<String, Long> getId(com.palominocia.JooqProject.modelo.tables.pojos.RolesUsuario object) {
        return compositeKeyRecord(object.getIdUsuario(), object.getIdRol());
    }

    /**
     * Fetch records that have <code>ID_USUARIO IN (values)</code>
     */
    public List<com.palominocia.JooqProject.modelo.tables.pojos.RolesUsuario> fetchByIdUsuario(String... values) {
        return fetch(RolesUsuario.ROLES_USUARIO.ID_USUARIO, values);
    }

    /**
     * Fetch records that have <code>ID_ROL IN (values)</code>
     */
    public List<com.palominocia.JooqProject.modelo.tables.pojos.RolesUsuario> fetchByIdRol(Long... values) {
        return fetch(RolesUsuario.ROLES_USUARIO.ID_ROL, values);
    }
}
