/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * uno.java
 *
 * Created on 10/04/2010, 12:23:45 PM
 */



import java.io.*;

/**
 *
 * @author JONATHAN
 */
public class uno extends javax.swing.JFrame {

    /** Creates new form uno */
    public uno() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
              new  FileDrop( new uno(), new FileDrop.Listener()
      {   public void  filesDropped( File[] files )
          {
              for( int i = 0; i < files.length; i++ )
                {   try
                    {
                        System.out.println(files[i].getCanonicalPath());
                    }   // end try
                    catch( java.io.IOException e ) {}
                }   // end for: through each dropped file
          }   // end filesDropped
      }); // end FileDrop.Listener
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new uno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
