/*
 * This file is generated by jOOQ.
*/
package com.palominocia.JooqProject.modelo.tables;


import com.palominocia.JooqProject.modelo.Autentificacion;
import com.palominocia.JooqProject.modelo.Keys;
import com.palominocia.JooqProject.modelo.tables.records.RolesGruposRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RolesGrupos extends TableImpl<RolesGruposRecord> {

    private static final long serialVersionUID = -424124888;

    /**
     * The reference instance of <code>autentificacion.ROLES_GRUPOS</code>
     */
    public static final RolesGrupos ROLES_GRUPOS = new RolesGrupos();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RolesGruposRecord> getRecordType() {
        return RolesGruposRecord.class;
    }

    /**
     * The column <code>autentificacion.ROLES_GRUPOS.ID_ROL</code>.
     */
    public final TableField<RolesGruposRecord, Long> ID_ROL = createField("ID_ROL", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>autentificacion.ROLES_GRUPOS.ID_GRUPO</code>.
     */
    public final TableField<RolesGruposRecord, Long> ID_GRUPO = createField("ID_GRUPO", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>autentificacion.ROLES_GRUPOS</code> table reference
     */
    public RolesGrupos() {
        this(DSL.name("ROLES_GRUPOS"), null);
    }

    /**
     * Create an aliased <code>autentificacion.ROLES_GRUPOS</code> table reference
     */
    public RolesGrupos(String alias) {
        this(DSL.name(alias), ROLES_GRUPOS);
    }

    /**
     * Create an aliased <code>autentificacion.ROLES_GRUPOS</code> table reference
     */
    public RolesGrupos(Name alias) {
        this(alias, ROLES_GRUPOS);
    }

    private RolesGrupos(Name alias, Table<RolesGruposRecord> aliased) {
        this(alias, aliased, null);
    }

    private RolesGrupos(Name alias, Table<RolesGruposRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Autentificacion.AUTENTIFICACION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RolesGruposRecord> getPrimaryKey() {
        return Keys.ROLES_GRUPOS_PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RolesGruposRecord>> getKeys() {
        return Arrays.<UniqueKey<RolesGruposRecord>>asList(Keys.ROLES_GRUPOS_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<RolesGruposRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<RolesGruposRecord, ?>>asList(Keys.ROLES_GRUPOS__FK_ROLES_GRUPOS, Keys.ROLES_GRUPOS__FK_GRUPOS_ROLES);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RolesGrupos as(String alias) {
        return new RolesGrupos(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RolesGrupos as(Name alias) {
        return new RolesGrupos(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public RolesGrupos rename(String name) {
        return new RolesGrupos(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RolesGrupos rename(Name name) {
        return new RolesGrupos(name, null);
    }
}
