/*
 * This file is generated by jOOQ.
*/
package com.palominocia.JooqProject.modelo.tables.daos;


import com.palominocia.JooqProject.modelo.tables.RolesGrupos;
import com.palominocia.JooqProject.modelo.tables.records.RolesGruposRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RolesGruposDao extends DAOImpl<RolesGruposRecord, com.palominocia.JooqProject.modelo.tables.pojos.RolesGrupos, Record2<Long, Long>> {

    /**
     * Create a new RolesGruposDao without any configuration
     */
    public RolesGruposDao() {
        super(RolesGrupos.ROLES_GRUPOS, com.palominocia.JooqProject.modelo.tables.pojos.RolesGrupos.class);
    }

    /**
     * Create a new RolesGruposDao with an attached configuration
     */
    public RolesGruposDao(Configuration configuration) {
        super(RolesGrupos.ROLES_GRUPOS, com.palominocia.JooqProject.modelo.tables.pojos.RolesGrupos.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Record2<Long, Long> getId(com.palominocia.JooqProject.modelo.tables.pojos.RolesGrupos object) {
        return compositeKeyRecord(object.getIdRol(), object.getIdGrupo());
    }

    /**
     * Fetch records that have <code>ID_ROL IN (values)</code>
     */
    public List<com.palominocia.JooqProject.modelo.tables.pojos.RolesGrupos> fetchByIdRol(Long... values) {
        return fetch(RolesGrupos.ROLES_GRUPOS.ID_ROL, values);
    }

    /**
     * Fetch records that have <code>ID_GRUPO IN (values)</code>
     */
    public List<com.palominocia.JooqProject.modelo.tables.pojos.RolesGrupos> fetchByIdGrupo(Long... values) {
        return fetch(RolesGrupos.ROLES_GRUPOS.ID_GRUPO, values);
    }
}
