/*
 * This file is generated by jOOQ.
*/
package com.palominocia.JooqProject.modelo.tables.daos;


import com.palominocia.JooqProject.modelo.tables.UsuarioTransaccion;
import com.palominocia.JooqProject.modelo.tables.records.UsuarioTransaccionRecord;

import java.sql.Date;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsuarioTransaccionDao extends DAOImpl<UsuarioTransaccionRecord, com.palominocia.JooqProject.modelo.tables.pojos.UsuarioTransaccion, Record2<Long, String>> {

    /**
     * Create a new UsuarioTransaccionDao without any configuration
     */
    public UsuarioTransaccionDao() {
        super(UsuarioTransaccion.USUARIO_TRANSACCION, com.palominocia.JooqProject.modelo.tables.pojos.UsuarioTransaccion.class);
    }

    /**
     * Create a new UsuarioTransaccionDao with an attached configuration
     */
    public UsuarioTransaccionDao(Configuration configuration) {
        super(UsuarioTransaccion.USUARIO_TRANSACCION, com.palominocia.JooqProject.modelo.tables.pojos.UsuarioTransaccion.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Record2<Long, String> getId(com.palominocia.JooqProject.modelo.tables.pojos.UsuarioTransaccion object) {
        return compositeKeyRecord(object.getIdTransaccion(), object.getIdUsuario());
    }

    /**
     * Fetch records that have <code>ID_TRANSACCION IN (values)</code>
     */
    public List<com.palominocia.JooqProject.modelo.tables.pojos.UsuarioTransaccion> fetchByIdTransaccion(Long... values) {
        return fetch(UsuarioTransaccion.USUARIO_TRANSACCION.ID_TRANSACCION, values);
    }

    /**
     * Fetch records that have <code>DIRECCION_IP IN (values)</code>
     */
    public List<com.palominocia.JooqProject.modelo.tables.pojos.UsuarioTransaccion> fetchByDireccionIp(String... values) {
        return fetch(UsuarioTransaccion.USUARIO_TRANSACCION.DIRECCION_IP, values);
    }

    /**
     * Fetch records that have <code>FEC_ULTIMO_LOGIN IN (values)</code>
     */
    public List<com.palominocia.JooqProject.modelo.tables.pojos.UsuarioTransaccion> fetchByFecUltimoLogin(Date... values) {
        return fetch(UsuarioTransaccion.USUARIO_TRANSACCION.FEC_ULTIMO_LOGIN, values);
    }

    /**
     * Fetch records that have <code>ID_USUARIO IN (values)</code>
     */
    public List<com.palominocia.JooqProject.modelo.tables.pojos.UsuarioTransaccion> fetchByIdUsuario(String... values) {
        return fetch(UsuarioTransaccion.USUARIO_TRANSACCION.ID_USUARIO, values);
    }
}
