/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Reproductor.Interfaz;

import Reproductor.Dialogos.Acerca;
import Reproductor.Librerias.Archivo;
import Reproductor.Librerias.Cargar_audio;
import Reproductor.Librerias.Libreria_Tabla;
import Reproductor.Librerias.ListaDobleConOrden;
import Reproductor.Librerias.NodoDoble;
import Reproductor.Librerias.Propiedades;
import Reproductor.Librerias.TrayIcon;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.HeadlessException;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javazoom.jlgui.player.amp.visual.ui.SpectrumTimeAnalyzer;

/**
 *
 * @author JONATHAN
 */
public class Gui_play extends javax.swing.JFrame {

    Desktop elemento;
    private UIManager.LookAndFeelInfo apariencias[];
    public static ListaDobleConOrden ldco = new ListaDobleConOrden();
    public boolean estado = false, repetir = false, aleatorio = false, estado1 = false, listado = false, equalizador = false, repetir_Cancion = false;
    public boolean duplicado = false;
    String nombre1;
    public int control1 = 0, veces = 0, tipo;
    public boolean noreproducible = false;
    public String ultima_direccion = "C:", ultima_lista = "C:";
    int valor_volumen = 50;
    Archivo archivo;
    private Cargar_audio audio;
    public static Propiedades propiedades_conf;
    private Libreria_Tabla lib_tabla;
    Info panel_info;
    TrayIcon icono;
    /**
     * Creates new form Gui_play
     */
    public Gui_play() {
        initComponents();
        propiedades_conf = new Propiedades();
        archivo = new Archivo();
        propiedades_conf.setClaseMaestra(this);
        propiedades_conf.Acceder_Conf();
        propiedades_conf.CARGAR_CONFIGURACIONES();
        
        audio = new Cargar_audio();
        audio.setClaseMaestra(this);
        audio.setPropiedades_conf(propiedades_conf);
        
        icono= new TrayIcon();
        icono.setClaseMaestra(this);
        
        lib_tabla = new Libreria_Tabla();
        lib_tabla.setClaseMaestra(this);
        lib_tabla.inicializarVarTabla();
        lib_tabla.setExtension(propiedades_conf.extencion_archivo);
        
        archivo.setPropiedades_conf(propiedades_conf);
        archivo.setTabla(lib_tabla);

        elemento = Desktop.getDesktop();
        /*Verifica que el ambiente del SO soporte los procedimientos*/
        if (elemento.isDesktopSupported() == false) {
            JOptionPane.showMessageDialog(this, "El sistema no soporta los procedimientos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
                apariencias = UIManager.getInstalledLookAndFeels();
        this.addWindowListener(new WindowAdapter(){

            public void windowClosing(WindowEvent e) {
                icono.MinimizarAlReloj();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_espectro = new SpectrumTimeAnalyzer();
        Progreso_percent = new javax.swing.JLabel();
        txtBit = new javax.swing.JTextField();
        BtnDetalles = new javax.swing.JButton();
        btnLista = new javax.swing.JButton();
        btnEqualizador = new javax.swing.JButton();
        Posicion = new javax.swing.JTextField();
        Progreso1 = new javax.swing.JSlider();
        btnPlay = new javax.swing.JButton();
        btnAbrir = new javax.swing.JButton();
        txtInformacion = new javax.swing.JTextField();
        btnSiguiente = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnPausa = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        Volumen = new javax.swing.JSlider();
        SPEAKER = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuPArchivo = new javax.swing.JMenu();
        MenuArchivo = new javax.swing.JMenuItem();
        Menu_Carpeta = new javax.swing.JMenuItem();
        menuURL = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        MenuOcultar = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenuItem();
        MenuLista = new javax.swing.JMenu();
        OpcionLista = new javax.swing.JMenu();
        PermitirDuplicado = new javax.swing.JRadioButtonMenuItem();
        EliminarDuplicadoAuto = new javax.swing.JRadioButtonMenuItem();
        EliminarDuplicadoDespues = new javax.swing.JRadioButtonMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        PermitirIrre = new javax.swing.JRadioButtonMenuItem();
        EliminarIrreAuto = new javax.swing.JRadioButtonMenuItem();
        EliminarIrreAhora = new javax.swing.JRadioButtonMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        Buscar = new javax.swing.JMenuItem();
        EliminarElegido = new javax.swing.JMenuItem();
        EliminarTodo = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        CargarLista = new javax.swing.JMenuItem();
        GuardarLista = new javax.swing.JMenuItem();
        MenuOpciones = new javax.swing.JMenu();
        RepetirLista = new javax.swing.JRadioButtonMenuItem();
        NoRepetir = new javax.swing.JRadioButtonMenuItem();
        RepetirAleatorio = new javax.swing.JRadioButtonMenuItem();
        MenuCancion = new javax.swing.JCheckBoxMenuItem();
        Modo_Presentacion = new javax.swing.JCheckBoxMenuItem();
        MenuAyuda = new javax.swing.JMenu();
        AcercaDE = new javax.swing.JMenuItem();
        Web = new javax.swing.JMenuItem();
        Contactar = new javax.swing.JMenuItem();
        MenuTema = new javax.swing.JMenu();
        TipoWindows = new javax.swing.JCheckBoxMenuItem();
        TipoRedondo = new javax.swing.JCheckBoxMenuItem();
        TipoJava = new javax.swing.JCheckBoxMenuItem();

        SpectrumTimeAnalyzer analyzer = (SpectrumTimeAnalyzer) Panel_espectro;
        analyzer.setDisplayMode(SpectrumTimeAnalyzer.DISPLAY_MODE_SCOPE);
        analyzer.setPeakColor(Color.red);
        analyzer.setBackground(Color.white);
        analyzer.setSpectrumAnalyserBandCount(19);
        analyzer.setSpectrumAnalyserDecay(0.05f);
        int fps = SpectrumTimeAnalyzer.DEFAULT_FPS;
        analyzer.setFps(fps);
        analyzer.setPeakDelay((int) (fps * SpectrumTimeAnalyzer.DEFAULT_SPECTRUM_ANALYSER_PEAK_DELAY_FPS_RATIO));
        Panel_espectro.setPreferredSize(new java.awt.Dimension(50, 65));

        javax.swing.GroupLayout Panel_espectroLayout = new javax.swing.GroupLayout(Panel_espectro);
        Panel_espectro.setLayout(Panel_espectroLayout);
        Panel_espectroLayout.setHorizontalGroup(
            Panel_espectroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 327, Short.MAX_VALUE)
        );
        Panel_espectroLayout.setVerticalGroup(
            Panel_espectroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 57, Short.MAX_VALUE)
        );

        Progreso_percent.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Progreso_percent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Progreso_percent.setText("0%");

        txtBit.setEditable(false);

        BtnDetalles.setText("Mas info");
        BtnDetalles.setToolTipText("Más Informacion");
        BtnDetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDetallesActionPerformed(evt);
            }
        });

        btnLista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/palomino/multimedia/audio/iconos/play_list.png"))); // NOI18N
        btnLista.setToolTipText("Lista de Musica");
        btnLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaActionPerformed(evt);
            }
        });

        btnEqualizador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/palomino/multimedia/audio/iconos/ecualizador.png"))); // NOI18N
        btnEqualizador.setToolTipText("Equalizador");
        btnEqualizador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEqualizadorActionPerformed(evt);
            }
        });

        Posicion.setEditable(false);
        Posicion.setToolTipText("Posicion de pista");

        Progreso1.setValue(0);
        Progreso1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Progreso1MouseDragged(evt);
            }
        });

        btnPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/palomino/multimedia/audio/iconos/reproducir.JPG"))); // NOI18N
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        btnAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/palomino/multimedia/audio/iconos/abrir.JPG"))); // NOI18N
        btnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirActionPerformed(evt);
            }
        });

        txtInformacion.setEditable(false);
        txtInformacion.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        txtInformacion.setToolTipText("Informacion de titulo");

        btnSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/palomino/multimedia/audio/iconos/siguiente.JPG"))); // NOI18N
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        btnAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/palomino/multimedia/audio/iconos/anterior.JPG"))); // NOI18N
        btnAnterior.setToolTipText("atraz");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnPausa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/palomino/multimedia/audio/iconos/pausa.JPG"))); // NOI18N
        btnPausa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPausaActionPerformed(evt);
            }
        });

        btnStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/palomino/multimedia/audio/iconos/parar.JPG"))); // NOI18N
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        Volumen.setToolTipText("");
        Volumen.setValue(40);
        Volumen.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                VolumenMouseDragged(evt);
            }
        });

        SPEAKER.setIcon(new javax.swing.ImageIcon(getClass().getResource("/palomino/multimedia/audio/iconos/speaker_alto.png"))); // NOI18N
        SPEAKER.setMaximumSize(new java.awt.Dimension(49, 25));
        SPEAKER.setMinimumSize(new java.awt.Dimension(49, 25));
        SPEAKER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SPEAKERActionPerformed(evt);
            }
        });

        MenuPArchivo.setText("Archivo");

        MenuArchivo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        MenuArchivo.setText("Añadir Archivo");
        MenuArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuArchivoActionPerformed(evt);
            }
        });
        MenuPArchivo.add(MenuArchivo);

        Menu_Carpeta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        Menu_Carpeta.setText("Añadir Carpeta");
        Menu_Carpeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_CarpetaActionPerformed(evt);
            }
        });
        MenuPArchivo.add(Menu_Carpeta);

        menuURL.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK));
        menuURL.setText("Añadir Direccion");
        menuURL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuURLActionPerformed(evt);
            }
        });
        MenuPArchivo.add(menuURL);
        MenuPArchivo.add(jSeparator4);

        MenuOcultar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, 0));
        MenuOcultar.setText("Ocultar Reproductor");
        MenuOcultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuOcultarActionPerformed(evt);
            }
        });
        MenuPArchivo.add(MenuOcultar);

        menuSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        menuSalir.setText("Salir");
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        MenuPArchivo.add(menuSalir);

        jMenuBar1.add(MenuPArchivo);

        MenuLista.setText("Lista");

        OpcionLista.setText("Opciones");

        PermitirDuplicado.setSelected(true);
        PermitirDuplicado.setText("Permitir Entradas duplicadas");
        PermitirDuplicado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PermitirDuplicadoActionPerformed(evt);
            }
        });
        OpcionLista.add(PermitirDuplicado);

        EliminarDuplicadoAuto.setText("Eliminar Duplicados Automaticamente");
        EliminarDuplicadoAuto.setToolTipText("Eliminara elementos luego de una agregacion");
        EliminarDuplicadoAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarDuplicadoAutoActionPerformed(evt);
            }
        });
        OpcionLista.add(EliminarDuplicadoAuto);

        EliminarDuplicadoDespues.setText("Eliminar Duplicados Ahora");
        EliminarDuplicadoDespues.setToolTipText("Busca y elimina elementos duplicados");
        EliminarDuplicadoDespues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarDuplicadoDespuesActionPerformed(evt);
            }
        });
        OpcionLista.add(EliminarDuplicadoDespues);
        OpcionLista.add(jSeparator2);

        PermitirIrre.setSelected(true);
        PermitirIrre.setText("Permitir Irreproducibles");
        PermitirIrre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PermitirIrreActionPerformed(evt);
            }
        });
        OpcionLista.add(PermitirIrre);

        EliminarIrreAuto.setText("Eliminar Irreproducibles Automaticamente");
        EliminarIrreAuto.setToolTipText("Funcionara luego de agregar algun elemento");
        EliminarIrreAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarIrreAutoActionPerformed(evt);
            }
        });
        OpcionLista.add(EliminarIrreAuto);

        EliminarIrreAhora.setText("Eliminar Irreproducibles Ahora");
        EliminarIrreAhora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarIrreAhoraActionPerformed(evt);
            }
        });
        OpcionLista.add(EliminarIrreAhora);
        OpcionLista.add(jSeparator3);

        Buscar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, 0));
        Buscar.setText("Saltar a Musica");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        OpcionLista.add(Buscar);

        MenuLista.add(OpcionLista);

        EliminarElegido.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, 0));
        EliminarElegido.setText("Eliminar Seleccionado");
        EliminarElegido.setEnabled(false);
        EliminarElegido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarElegidoActionPerformed(evt);
            }
        });
        MenuLista.add(EliminarElegido);

        EliminarTodo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, java.awt.event.InputEvent.CTRL_MASK));
        EliminarTodo.setText("Eliminar todo");
        EliminarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarTodoActionPerformed(evt);
            }
        });
        MenuLista.add(EliminarTodo);
        MenuLista.add(jSeparator1);

        CargarLista.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        CargarLista.setText("Cargar Lista");
        CargarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarListaActionPerformed(evt);
            }
        });
        MenuLista.add(CargarLista);

        GuardarLista.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        GuardarLista.setText("Guardar Lista");
        GuardarLista.setEnabled(false);
        GuardarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarListaActionPerformed(evt);
            }
        });
        MenuLista.add(GuardarLista);

        jMenuBar1.add(MenuLista);

        MenuOpciones.setText("Opciones");

        RepetirLista.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, 0));
        RepetirLista.setText("Repetir Lista");
        RepetirLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RepetirListaActionPerformed(evt);
            }
        });
        MenuOpciones.add(RepetirLista);

        NoRepetir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, 0));
        NoRepetir.setSelected(true);
        NoRepetir.setText("No Repetir Lista");
        NoRepetir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoRepetirActionPerformed(evt);
            }
        });
        MenuOpciones.add(NoRepetir);

        RepetirAleatorio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, 0));
        RepetirAleatorio.setText("Repetir Aleatorio");
        RepetirAleatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RepetirAleatorioActionPerformed(evt);
            }
        });
        MenuOpciones.add(RepetirAleatorio);

        MenuCancion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, 0));
        MenuCancion.setText("Repetir Cancion");
        MenuCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCancionActionPerformed(evt);
            }
        });
        MenuOpciones.add(MenuCancion);

        Modo_Presentacion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        Modo_Presentacion.setText("Modo Presentacion");
        Modo_Presentacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Modo_PresentacionActionPerformed(evt);
            }
        });
        MenuOpciones.add(Modo_Presentacion);

        jMenuBar1.add(MenuOpciones);

        MenuAyuda.setText("Ayuda");

        AcercaDE.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        AcercaDE.setText("Acerca de:");
        AcercaDE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcercaDEActionPerformed(evt);
            }
        });
        MenuAyuda.add(AcercaDE);

        Web.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        Web.setText("Web");
        Web.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WebActionPerformed(evt);
            }
        });
        MenuAyuda.add(Web);

        Contactar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, 0));
        Contactar.setText("Contactar");
        Contactar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactarActionPerformed(evt);
            }
        });
        MenuAyuda.add(Contactar);

        MenuTema.setText("Tema Visual");

        TipoWindows.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, 0));
        TipoWindows.setText("Tipo Windows");
        TipoWindows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoWindowsActionPerformed(evt);
            }
        });
        MenuTema.add(TipoWindows);

        TipoRedondo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, 0));
        TipoRedondo.setText("Tipo Redondeado suave");
        TipoRedondo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoRedondoActionPerformed(evt);
            }
        });
        MenuTema.add(TipoRedondo);

        TipoJava.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, 0));
        TipoJava.setSelected(true);
        TipoJava.setText("Tipo Java");
        TipoJava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoJavaActionPerformed(evt);
            }
        });
        MenuTema.add(TipoJava);

        MenuAyuda.add(MenuTema);

        jMenuBar1.add(MenuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Progreso1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Progreso_percent, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAbrir, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnStop, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPausa, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 224, Short.MAX_VALUE)
                        .addComponent(SPEAKER, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Volumen, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtInformacion, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnDetalles)
                                .addGap(32, 32, 32)
                                .addComponent(btnLista, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnEqualizador, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Posicion, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtBit, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Panel_espectro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Volumen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPlay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnStop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAbrir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPausa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAnterior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSiguiente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SPEAKER, 0, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Posicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnLista, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnEqualizador, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(BtnDetalles, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Panel_espectro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Progreso1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Progreso_percent, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuArchivoActionPerformed
        archivo.ABRIR("Archivos", ultima_direccion);
    }//GEN-LAST:event_MenuArchivoActionPerformed

    private void Menu_CarpetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_CarpetaActionPerformed
        archivo.ABRIR("Carpeta", ultima_direccion);
    }//GEN-LAST:event_Menu_CarpetaActionPerformed

    private void menuURLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuURLActionPerformed
         URL direccion = null;
         String direccionS = JOptionPane.showInputDialog(null, "Ingrese aqui la URL a reproducir" + "\n" + "Por ejemplo www.musica.com/archivo.mp3", "Abrir URL", JOptionPane.NO_OPTION);
         int desicion = JOptionPane.showOptionDialog(null, "Desea reproducirlo o agregarlo", "Elija", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null);
         if (desicion == 1) {
         //agregar
         }
         else {
         CARGAR_DIRECCION_INT(direccionS, direccion);
         }
    }//GEN-LAST:event_menuURLActionPerformed

    private void MenuOcultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuOcultarActionPerformed
        icono.MinimizarAlReloj();
    }//GEN-LAST:event_MenuOcultarActionPerformed

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuSalirActionPerformed

    private void PermitirDuplicadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PermitirDuplicadoActionPerformed
        duplicado = false;
        EliminarDuplicadoAuto.setSelected(false);
        EliminarDuplicadoDespues.setSelected(false);
    }//GEN-LAST:event_PermitirDuplicadoActionPerformed

    private void EliminarDuplicadoAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarDuplicadoAutoActionPerformed
        duplicado = true;
        PermitirDuplicado.setSelected(false);
        EliminarDuplicadoDespues.setSelected(false);
    }//GEN-LAST:event_EliminarDuplicadoAutoActionPerformed

    private void EliminarDuplicadoDespuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarDuplicadoDespuesActionPerformed
        PermitirDuplicado.setSelected(false);
        EliminarDuplicadoAuto.setSelected(false);
        //metodos_internos.BuscarDuplicaddos(ldco);
        //Hace q regrese a la primera opcion
        PermitirDuplicado.setSelected(true);
        EliminarDuplicadoDespues.setSelected(false);
    }//GEN-LAST:event_EliminarDuplicadoDespuesActionPerformed

    private void PermitirIrreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PermitirIrreActionPerformed
        noreproducible = false;
        EliminarIrreAuto.setSelected(false);
        EliminarIrreAhora.setSelected(false);
    }//GEN-LAST:event_PermitirIrreActionPerformed

    private void EliminarIrreAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarIrreAutoActionPerformed
        noreproducible = true;
        EliminarIrreAhora.setSelected(false);
        PermitirIrre.setSelected(false);
    }//GEN-LAST:event_EliminarIrreAutoActionPerformed

    private void EliminarIrreAhoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarIrreAhoraActionPerformed
        Libreria_Tabla.BuscarIrreproducibles();
        EliminarIrreAuto.setSelected(true);
        noreproducible = true;
        EliminarIrreAhora.setSelected(false);
        PermitirIrre.setSelected(false);
        JOptionPane.showMessageDialog(null, "Se eliminaron " + Libreria_Tabla.eliminados + " elementos de la lista", "Advertencia", JOptionPane.INFORMATION_MESSAGE);
        Libreria_Tabla.eliminados = 0;
    }//GEN-LAST:event_EliminarIrreAhoraActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        Busqueda bus = new Busqueda(ldco);
        bus.setAudio(getAudio());
        bus.show();
    }//GEN-LAST:event_BuscarActionPerformed

    private void EliminarElegidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarElegidoActionPerformed
        Eliminar_Item();
    }//GEN-LAST:event_EliminarElegidoActionPerformed

    private void EliminarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarTodoActionPerformed
        ldco.setInicio(null);
        Libreria_Tabla.inicializaTabla();
        Habilitar(false);
        getAudio().parar();
        Progreso1.setValue(0);
        Posicion.setText("");
        txtInformacion.setText("");
    }//GEN-LAST:event_EliminarTodoActionPerformed

    private void CargarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarListaActionPerformed
        archivo.CargarLista(ultima_lista);
        Habilitar(true);
    }//GEN-LAST:event_CargarListaActionPerformed

    private void GuardarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarListaActionPerformed
        archivo.GuardarLista(ldco, ultima_lista);
    }//GEN-LAST:event_GuardarListaActionPerformed

    private void RepetirListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RepetirListaActionPerformed
        NoRepetir.setSelected(false);
        RepetirAleatorio.setSelected(false);
        repetir = true;
        aleatorio = false;
        control1 = 0;
    }//GEN-LAST:event_RepetirListaActionPerformed

    private void NoRepetirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoRepetirActionPerformed
        RepetirAleatorio.setSelected(false);
        RepetirLista.setSelected(false);
        repetir = false;
        aleatorio = false;
        control1 = 0;
    }//GEN-LAST:event_NoRepetirActionPerformed

    private void RepetirAleatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RepetirAleatorioActionPerformed
        NoRepetir.setSelected(false);
        RepetirLista.setSelected(false);
        aleatorio = true;
        repetir = false;
        control1 = 1;
    }//GEN-LAST:event_RepetirAleatorioActionPerformed

    private void MenuCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCancionActionPerformed
        repetir_Cancion = !repetir_Cancion;
    }//GEN-LAST:event_MenuCancionActionPerformed

    private void Modo_PresentacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Modo_PresentacionActionPerformed
        // solo reproducir 15 segundos y saltar
        if (!Modo_Presentacion.isSelected()) {
            JOptionPane.showConfirmDialog(null, "De este modo se desactiva reproduccion un 10% del audio", "Aviso", JOptionPane.DEFAULT_OPTION);
            try {
                getPropiedades_conf().GUARDAR_ULTIMO_MODO(Modo_Presentacion.isSelected());
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Gui_play.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (Modo_Presentacion.isSelected()) {
            JOptionPane.showConfirmDialog(null, "De este modo solo reproducira un 10% del audio", "Aviso", JOptionPane.DEFAULT_OPTION);
            try {
                getPropiedades_conf().GUARDAR_ULTIMO_MODO(Modo_Presentacion.isSelected());
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Gui_play.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_Modo_PresentacionActionPerformed

    private void AcercaDEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcercaDEActionPerformed
        Acerca objeto_panel = new Acerca();
        JOptionPane.showMessageDialog(this, objeto_panel, "Acerca de:", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_AcercaDEActionPerformed

    private void WebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WebActionPerformed
        Aparecer();
    }//GEN-LAST:event_WebActionPerformed

    private void ContactarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactarActionPerformed
        Contactar();
    }//GEN-LAST:event_ContactarActionPerformed

    private void TipoWindowsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoWindowsActionPerformed
        TipoRedondo.setSelected(false);
        TipoJava.setSelected(false);
        tipo = 3;
        CambiarApariencia(tipo);
    }//GEN-LAST:event_TipoWindowsActionPerformed

    private void TipoRedondoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoRedondoActionPerformed
        TipoWindows.setSelected(false);
        TipoJava.setSelected(false);
        tipo = 1;
        CambiarApariencia(tipo);
    }//GEN-LAST:event_TipoRedondoActionPerformed

    private void TipoJavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoJavaActionPerformed
        TipoRedondo.setSelected(false);
        TipoWindows.setSelected(false);
        tipo = 0;
        CambiarApariencia(tipo);
    }//GEN-LAST:event_TipoJavaActionPerformed

    private void BtnDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDetallesActionPerformed
        Mostrar_info();
    }//GEN-LAST:event_BtnDetallesActionPerformed

    private void btnListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaActionPerformed
        listado = !listado;
        if (listado) {
            lib_tabla.getVariable_tabla().setVisible(true);
            //Libreria_Tabla.getVariable_tabla().setVisible(true);
        } else {
            lib_tabla.getVariable_tabla().setVisible(false);
            //Libreria_Tabla.getVariable_tabla().setVisible(false);
        }
    }//GEN-LAST:event_btnListaActionPerformed

    private void btnEqualizadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEqualizadorActionPerformed
        equalizador = !equalizador;
         if (equalizador) {
         getAudio().getEqualizar().setVisible(true);
         }
         else {
         getAudio().getEqualizar().setVisible(false);
         }
    }//GEN-LAST:event_btnEqualizadorActionPerformed

    private void Progreso1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Progreso1MouseDragged
        getAudio().MOVIDA_MOUSE(SPEAKER, Progreso1, Volumen);
    }//GEN-LAST:event_Progreso1MouseDragged

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        getAudio().SeleccionarArchivo();
    }//GEN-LAST:event_btnPlayActionPerformed

    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed
        archivo.ABRIR("Archivos", ultima_direccion);
    }//GEN-LAST:event_btnAbrirActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        try {
            getAudio().SiguienteAnterior(1, control1);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "No encuentro pista", "Error de usuario", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        try {
            getAudio().SiguienteAnterior(0, control1);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "No encuentro pista", "Error de usuario", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnPausaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPausaActionPerformed

        estado = !estado;
        if (estado) {
            getAudio().pausar();
        } else {
            getAudio().resumir();
        }
    }//GEN-LAST:event_btnPausaActionPerformed

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        getAudio().parar();
        SPEAKER.setIcon(new ImageIcon(getClass().getResource("/palomino/multimedia/audio/iconos/speaker_bajo.png")));
        getAudio().secondsAmount = 0;
        SpectrumTimeAnalyzer analizer = (SpectrumTimeAnalyzer) Panel_espectro;
        analizer.stopDSP();
        analizer.closeDSP();
    }//GEN-LAST:event_btnStopActionPerformed

    private void VolumenMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VolumenMouseDragged
        getAudio().ModificarVolumen(Volumen);
    }//GEN-LAST:event_VolumenMouseDragged

    private void SPEAKERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SPEAKERActionPerformed
        estado1 = !estado1;
        getAudio().BOTON_MUTE_N(estado1, SPEAKER, Volumen);
    }//GEN-LAST:event_SPEAKERActionPerformed
    public void CambiarApariencia(int i) {
        try {
            UIManager.setLookAndFeel(apariencias[i].getClassName());
            SwingUtilities.updateComponentTreeUI(this);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Imposible modificar el tema visual", "Lookandfeel inválido.",
                    JOptionPane.ERROR_MESSAGE);
        }
    }
        public void Contactar() {

        String email = email = "jonathan.palomino.vilca@gmail.com";
        String mail = "mailto:" + email;
        try {
            elemento.mail(new URI(mail));
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error inesperado", "Error", JOptionPane.ERROR_MESSAGE);
        }


    }
    public void Aparecer() {
        try {
            try {
                elemento.browse(new URI("http://jonathan-palomino.blogspot.com/"));
            }
            catch (IOException ex) {
                Logger.getLogger(Gui_play.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        catch (URISyntaxException ex) {
            JOptionPane.showMessageDialog(null, "Error de web");
        }
    }
    public void Mostrar_info() {
        try {
            String audioformato = (String) getAudio().audioInfo.get("audio.type");
            if (audioformato.equalsIgnoreCase("mp3")) {
                panel_info = new Info(getAudio().mpeg);
                JOptionPane.showMessageDialog(this, panel_info, "Informacion de Archivo", JOptionPane.INFORMATION_MESSAGE);
            } else if (audioformato.equalsIgnoreCase("ogg")) {
                panel_info = new Info(getAudio().ogg);
                JOptionPane.showMessageDialog(this, panel_info, "Informacion de Archivo", JOptionPane.INFORMATION_MESSAGE);
            } else if (audioformato.equalsIgnoreCase("flac")) {
                panel_info = new Info(getAudio().fla);
                JOptionPane.showMessageDialog(this, panel_info, "Informacion de Archivo", JOptionPane.INFORMATION_MESSAGE);
            } else if (audioformato.equalsIgnoreCase("ape")) {
                panel_info = new Info(getAudio().ape);
                JOptionPane.showMessageDialog(this, panel_info, "Informacion de Archivo", JOptionPane.INFORMATION_MESSAGE);
            } else if (audioformato.equalsIgnoreCase("wave")) {
                panel_info = new Info(getAudio().wav);
                JOptionPane.showMessageDialog(this, panel_info, "Informacion de Archivo", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Reprodusca primero el archivo por favor", "Error de Usuario", JOptionPane.WARNING_MESSAGE);
        }
    }

    public static void Habilitar(boolean b) {
        EliminarElegido.setEnabled(b);
        EliminarTodo.setEnabled(b);
        GuardarLista.setEnabled(b);
    }

    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui_play().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AcercaDE;
    private javax.swing.JButton BtnDetalles;
    public javax.swing.JMenuItem Buscar;
    public static javax.swing.JMenuItem CargarLista;
    private javax.swing.JMenuItem Contactar;
    public javax.swing.JRadioButtonMenuItem EliminarDuplicadoAuto;
    public javax.swing.JRadioButtonMenuItem EliminarDuplicadoDespues;
    public static javax.swing.JMenuItem EliminarElegido;
    private javax.swing.JRadioButtonMenuItem EliminarIrreAhora;
    private javax.swing.JRadioButtonMenuItem EliminarIrreAuto;
    public static javax.swing.JMenuItem EliminarTodo;
    public static javax.swing.JMenuItem GuardarLista;
    private javax.swing.JMenuItem MenuArchivo;
    private javax.swing.JMenu MenuAyuda;
    private javax.swing.JCheckBoxMenuItem MenuCancion;
    private javax.swing.JMenu MenuLista;
    private javax.swing.JMenuItem MenuOcultar;
    private javax.swing.JMenu MenuOpciones;
    private javax.swing.JMenu MenuPArchivo;
    private javax.swing.JMenu MenuTema;
    private javax.swing.JMenuItem Menu_Carpeta;
    public javax.swing.JCheckBoxMenuItem Modo_Presentacion;
    private javax.swing.JRadioButtonMenuItem NoRepetir;
    public javax.swing.JMenu OpcionLista;
    public javax.swing.JPanel Panel_espectro;
    public javax.swing.JRadioButtonMenuItem PermitirDuplicado;
    private javax.swing.JRadioButtonMenuItem PermitirIrre;
    public javax.swing.JTextField Posicion;
    public javax.swing.JSlider Progreso1;
    public javax.swing.JLabel Progreso_percent;
    private javax.swing.JRadioButtonMenuItem RepetirAleatorio;
    private javax.swing.JRadioButtonMenuItem RepetirLista;
    public javax.swing.JButton SPEAKER;
    private javax.swing.JCheckBoxMenuItem TipoJava;
    private javax.swing.JCheckBoxMenuItem TipoRedondo;
    private javax.swing.JCheckBoxMenuItem TipoWindows;
    public javax.swing.JSlider Volumen;
    private javax.swing.JMenuItem Web;
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnEqualizador;
    private javax.swing.JButton btnLista;
    private javax.swing.JButton btnPausa;
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btnStop;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JMenuItem menuSalir;
    private javax.swing.JMenuItem menuURL;
    public javax.swing.JTextField txtBit;
    public javax.swing.JTextField txtInformacion;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the audio
     */
    public Cargar_audio getAudio() {
        return audio;
    }

    /**
     * @param audio the audio to set
     */
    public void setAudio(Cargar_audio audio) {
        this.audio = audio;
    }

    /**
     * @return the propiedades_conf
     */
    public Propiedades getPropiedades_conf() {
        return propiedades_conf;
    }

    /**
     * @param propiedades_conf the propiedades_conf to set
     */
    public void setPropiedades_conf(Propiedades propiedades_conf) {
        this.propiedades_conf = propiedades_conf;
    }

    public void Eliminar_Item() {
        //System.out.println(lib_tabla.rutaTabla);
        NodoDoble auxiliar = ldco.busca((File) lib_tabla.getVariable_tabla().rutaTabla);
        if (auxiliar != null) {
            ldco.elimina(auxiliar);
            Libreria_Tabla.ActualizaTabla();
        }
    }

    /**
     * @return the lib_tabla
     */
    public Libreria_Tabla getLib_tabla() {
        return lib_tabla;
    }

    /**
     * @param lib_tabla the lib_tabla to set
     */
    public void setLib_tabla(Libreria_Tabla lib_tabla) {
        this.lib_tabla = lib_tabla;
    }

   public void CARGAR_DIRECCION_INT(String direccionS, URL direccion) throws HeadlessException {
        try {
            direccion = new URL(direccionS);
        }
        catch (MalformedURLException ex) {
            JOptionPane.showMessageDialog(null, "Ingreso mal su URL");
        }
        Cargar_audio.loadFile(direccion);
        getAudio().reproducir();
        getAudio().ModificarVolumen(Volumen);
        getAudio().MOSTRARINFO(nombre1, direccionS, txtInformacion, Posicion, txtBit);
    }
}
