/*
 * This file is generated by jOOQ.
*/
package com.palominocia.JooqProject.modelo.tables.records;


import com.palominocia.JooqProject.modelo.tables.GrupoRecursos;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GrupoRecursosRecord extends UpdatableRecordImpl<GrupoRecursosRecord> implements Record2<Long, Long> {

    private static final long serialVersionUID = -1800172160;

    /**
     * Setter for <code>autentificacion.GRUPO_RECURSOS.ID_GRUPO</code>.
     */
    public void setIdGrupo(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>autentificacion.GRUPO_RECURSOS.ID_GRUPO</code>.
     */
    public Long getIdGrupo() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>autentificacion.GRUPO_RECURSOS.ID_RECURSO</code>.
     */
    public void setIdRecurso(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>autentificacion.GRUPO_RECURSOS.ID_RECURSO</code>.
     */
    public Long getIdRecurso() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return GrupoRecursos.GRUPO_RECURSOS.ID_GRUPO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return GrupoRecursos.GRUPO_RECURSOS.ID_RECURSO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getIdGrupo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getIdRecurso();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getIdGrupo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getIdRecurso();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GrupoRecursosRecord value1(Long value) {
        setIdGrupo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GrupoRecursosRecord value2(Long value) {
        setIdRecurso(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GrupoRecursosRecord values(Long value1, Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GrupoRecursosRecord
     */
    public GrupoRecursosRecord() {
        super(GrupoRecursos.GRUPO_RECURSOS);
    }

    /**
     * Create a detached, initialised GrupoRecursosRecord
     */
    public GrupoRecursosRecord(Long idGrupo, Long idRecurso) {
        super(GrupoRecursos.GRUPO_RECURSOS);

        set(0, idGrupo);
        set(1, idRecurso);
    }
}
