/*
 * This file is generated by jOOQ.
*/
package com.palominocia.JooqProject.modelo.tables.records;


import com.palominocia.JooqProject.modelo.tables.RolesGrupos;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RolesGruposRecord extends UpdatableRecordImpl<RolesGruposRecord> implements Record2<Long, Long> {

    private static final long serialVersionUID = -1074134996;

    /**
     * Setter for <code>autentificacion.ROLES_GRUPOS.ID_ROL</code>.
     */
    public void setIdRol(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>autentificacion.ROLES_GRUPOS.ID_ROL</code>.
     */
    public Long getIdRol() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>autentificacion.ROLES_GRUPOS.ID_GRUPO</code>.
     */
    public void setIdGrupo(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>autentificacion.ROLES_GRUPOS.ID_GRUPO</code>.
     */
    public Long getIdGrupo() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return RolesGrupos.ROLES_GRUPOS.ID_ROL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return RolesGrupos.ROLES_GRUPOS.ID_GRUPO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getIdRol();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getIdGrupo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getIdRol();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getIdGrupo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RolesGruposRecord value1(Long value) {
        setIdRol(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RolesGruposRecord value2(Long value) {
        setIdGrupo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RolesGruposRecord values(Long value1, Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RolesGruposRecord
     */
    public RolesGruposRecord() {
        super(RolesGrupos.ROLES_GRUPOS);
    }

    /**
     * Create a detached, initialised RolesGruposRecord
     */
    public RolesGruposRecord(Long idRol, Long idGrupo) {
        super(RolesGrupos.ROLES_GRUPOS);

        set(0, idRol);
        set(1, idGrupo);
    }
}
