/*
 * This file is generated by jOOQ.
*/
package com.palominocia.JooqProject.modelo.tables.records;


import com.palominocia.JooqProject.modelo.tables.UsuarioTransaccion;

import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsuarioTransaccionRecord extends UpdatableRecordImpl<UsuarioTransaccionRecord> implements Record4<Long, String, Date, String> {

    private static final long serialVersionUID = 1414230330;

    /**
     * Setter for <code>autentificacion.USUARIO_TRANSACCION.ID_TRANSACCION</code>.
     */
    public void setIdTransaccion(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>autentificacion.USUARIO_TRANSACCION.ID_TRANSACCION</code>.
     */
    public Long getIdTransaccion() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>autentificacion.USUARIO_TRANSACCION.DIRECCION_IP</code>.
     */
    public void setDireccionIp(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>autentificacion.USUARIO_TRANSACCION.DIRECCION_IP</code>.
     */
    public String getDireccionIp() {
        return (String) get(1);
    }

    /**
     * Setter for <code>autentificacion.USUARIO_TRANSACCION.FEC_ULTIMO_LOGIN</code>.
     */
    public void setFecUltimoLogin(Date value) {
        set(2, value);
    }

    /**
     * Getter for <code>autentificacion.USUARIO_TRANSACCION.FEC_ULTIMO_LOGIN</code>.
     */
    public Date getFecUltimoLogin() {
        return (Date) get(2);
    }

    /**
     * Setter for <code>autentificacion.USUARIO_TRANSACCION.ID_USUARIO</code>.
     */
    public void setIdUsuario(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>autentificacion.USUARIO_TRANSACCION.ID_USUARIO</code>.
     */
    public String getIdUsuario() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Long, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, String, Date, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, String, Date, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return UsuarioTransaccion.USUARIO_TRANSACCION.ID_TRANSACCION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return UsuarioTransaccion.USUARIO_TRANSACCION.DIRECCION_IP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field3() {
        return UsuarioTransaccion.USUARIO_TRANSACCION.FEC_ULTIMO_LOGIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return UsuarioTransaccion.USUARIO_TRANSACCION.ID_USUARIO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getIdTransaccion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getDireccionIp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component3() {
        return getFecUltimoLogin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getIdUsuario();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getIdTransaccion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getDireccionIp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value3() {
        return getFecUltimoLogin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getIdUsuario();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuarioTransaccionRecord value1(Long value) {
        setIdTransaccion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuarioTransaccionRecord value2(String value) {
        setDireccionIp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuarioTransaccionRecord value3(Date value) {
        setFecUltimoLogin(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuarioTransaccionRecord value4(String value) {
        setIdUsuario(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuarioTransaccionRecord values(Long value1, String value2, Date value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsuarioTransaccionRecord
     */
    public UsuarioTransaccionRecord() {
        super(UsuarioTransaccion.USUARIO_TRANSACCION);
    }

    /**
     * Create a detached, initialised UsuarioTransaccionRecord
     */
    public UsuarioTransaccionRecord(Long idTransaccion, String direccionIp, Date fecUltimoLogin, String idUsuario) {
        super(UsuarioTransaccion.USUARIO_TRANSACCION);

        set(0, idTransaccion);
        set(1, direccionIp);
        set(2, fecUltimoLogin);
        set(3, idUsuario);
    }
}
