/*
 * This file is generated by jOOQ.
*/
package com.palominocia.JooqProject.modelo;


import com.palominocia.JooqProject.modelo.tables.Clientes;
import com.palominocia.JooqProject.modelo.tables.GrupoRecursos;
import com.palominocia.JooqProject.modelo.tables.Grupos;
import com.palominocia.JooqProject.modelo.tables.OauthAccessToken;
import com.palominocia.JooqProject.modelo.tables.OauthClientDetails;
import com.palominocia.JooqProject.modelo.tables.OauthClientToken;
import com.palominocia.JooqProject.modelo.tables.OauthCode;
import com.palominocia.JooqProject.modelo.tables.OauthRefreshToken;
import com.palominocia.JooqProject.modelo.tables.Recursos;
import com.palominocia.JooqProject.modelo.tables.Roles;
import com.palominocia.JooqProject.modelo.tables.RolesGrupos;
import com.palominocia.JooqProject.modelo.tables.RolesUsuario;
import com.palominocia.JooqProject.modelo.tables.UsuarioTransaccion;
import com.palominocia.JooqProject.modelo.tables.Usuarios;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Autentificacion extends SchemaImpl {

    private static final long serialVersionUID = 255318402;

    /**
     * The reference instance of <code>autentificacion</code>
     */
    public static final Autentificacion AUTENTIFICACION = new Autentificacion();

    /**
     * The table <code>autentificacion.CLIENTES</code>.
     */
    public final Clientes CLIENTES = com.palominocia.JooqProject.modelo.tables.Clientes.CLIENTES;

    /**
     * The table <code>autentificacion.GRUPOS</code>.
     */
    public final Grupos GRUPOS = com.palominocia.JooqProject.modelo.tables.Grupos.GRUPOS;

    /**
     * The table <code>autentificacion.GRUPO_RECURSOS</code>.
     */
    public final GrupoRecursos GRUPO_RECURSOS = com.palominocia.JooqProject.modelo.tables.GrupoRecursos.GRUPO_RECURSOS;

    /**
     * The table <code>autentificacion.RECURSOS</code>.
     */
    public final Recursos RECURSOS = com.palominocia.JooqProject.modelo.tables.Recursos.RECURSOS;

    /**
     * The table <code>autentificacion.ROLES</code>.
     */
    public final Roles ROLES = com.palominocia.JooqProject.modelo.tables.Roles.ROLES;

    /**
     * The table <code>autentificacion.ROLES_GRUPOS</code>.
     */
    public final RolesGrupos ROLES_GRUPOS = com.palominocia.JooqProject.modelo.tables.RolesGrupos.ROLES_GRUPOS;

    /**
     * The table <code>autentificacion.ROLES_USUARIO</code>.
     */
    public final RolesUsuario ROLES_USUARIO = com.palominocia.JooqProject.modelo.tables.RolesUsuario.ROLES_USUARIO;

    /**
     * The table <code>autentificacion.USUARIOS</code>.
     */
    public final Usuarios USUARIOS = com.palominocia.JooqProject.modelo.tables.Usuarios.USUARIOS;

    /**
     * The table <code>autentificacion.USUARIO_TRANSACCION</code>.
     */
    public final UsuarioTransaccion USUARIO_TRANSACCION = com.palominocia.JooqProject.modelo.tables.UsuarioTransaccion.USUARIO_TRANSACCION;

    /**
     * The table <code>autentificacion.oauth_access_token</code>.
     */
    public final OauthAccessToken OAUTH_ACCESS_TOKEN = com.palominocia.JooqProject.modelo.tables.OauthAccessToken.OAUTH_ACCESS_TOKEN;

    /**
     * The table <code>autentificacion.oauth_client_details</code>.
     */
    public final OauthClientDetails OAUTH_CLIENT_DETAILS = com.palominocia.JooqProject.modelo.tables.OauthClientDetails.OAUTH_CLIENT_DETAILS;

    /**
     * The table <code>autentificacion.oauth_client_token</code>.
     */
    public final OauthClientToken OAUTH_CLIENT_TOKEN = com.palominocia.JooqProject.modelo.tables.OauthClientToken.OAUTH_CLIENT_TOKEN;

    /**
     * The table <code>autentificacion.oauth_code</code>.
     */
    public final OauthCode OAUTH_CODE = com.palominocia.JooqProject.modelo.tables.OauthCode.OAUTH_CODE;

    /**
     * The table <code>autentificacion.oauth_refresh_token</code>.
     */
    public final OauthRefreshToken OAUTH_REFRESH_TOKEN = com.palominocia.JooqProject.modelo.tables.OauthRefreshToken.OAUTH_REFRESH_TOKEN;

    /**
     * No further instances allowed
     */
    private Autentificacion() {
        super("autentificacion", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.CLIENTES_ID_CLIENTE_SEQ,
            Sequences.GRUPOS_ID_GRUPO_SEQ,
            Sequences.RECURSOS_ID_RECURSO_SEQ,
            Sequences.ROLES_ID_ROL_SEQ,
            Sequences.USUARIO_TRANSACCION_ID_TRANSACCION_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Clientes.CLIENTES,
            Grupos.GRUPOS,
            GrupoRecursos.GRUPO_RECURSOS,
            Recursos.RECURSOS,
            Roles.ROLES,
            RolesGrupos.ROLES_GRUPOS,
            RolesUsuario.ROLES_USUARIO,
            Usuarios.USUARIOS,
            UsuarioTransaccion.USUARIO_TRANSACCION,
            OauthAccessToken.OAUTH_ACCESS_TOKEN,
            OauthClientDetails.OAUTH_CLIENT_DETAILS,
            OauthClientToken.OAUTH_CLIENT_TOKEN,
            OauthCode.OAUTH_CODE,
            OauthRefreshToken.OAUTH_REFRESH_TOKEN);
    }
}
