/*
 * This file is generated by jOOQ.
*/
package com.palominocia.JooqProject.modelo;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in autentificacion
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>autentificacion.CLIENTES_ID_CLIENTE_seq</code>
     */
    public static final Sequence<Long> CLIENTES_ID_CLIENTE_SEQ = new SequenceImpl<Long>("CLIENTES_ID_CLIENTE_seq", Autentificacion.AUTENTIFICACION, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>autentificacion.GRUPOS_ID_GRUPO_seq</code>
     */
    public static final Sequence<Long> GRUPOS_ID_GRUPO_SEQ = new SequenceImpl<Long>("GRUPOS_ID_GRUPO_seq", Autentificacion.AUTENTIFICACION, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>autentificacion.RECURSOS_ID_RECURSO_seq</code>
     */
    public static final Sequence<Long> RECURSOS_ID_RECURSO_SEQ = new SequenceImpl<Long>("RECURSOS_ID_RECURSO_seq", Autentificacion.AUTENTIFICACION, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>autentificacion.ROLES_ID_ROL_seq</code>
     */
    public static final Sequence<Long> ROLES_ID_ROL_SEQ = new SequenceImpl<Long>("ROLES_ID_ROL_seq", Autentificacion.AUTENTIFICACION, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>autentificacion.USUARIO_TRANSACCION_ID_TRANSACCION_seq</code>
     */
    public static final Sequence<Long> USUARIO_TRANSACCION_ID_TRANSACCION_SEQ = new SequenceImpl<Long>("USUARIO_TRANSACCION_ID_TRANSACCION_seq", Autentificacion.AUTENTIFICACION, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
