/*
 * This file is generated by jOOQ.
*/
package com.palominocia.JooqProject.modelo;


import com.palominocia.JooqProject.modelo.tables.Clientes;
import com.palominocia.JooqProject.modelo.tables.GrupoRecursos;
import com.palominocia.JooqProject.modelo.tables.Grupos;
import com.palominocia.JooqProject.modelo.tables.OauthAccessToken;
import com.palominocia.JooqProject.modelo.tables.OauthClientDetails;
import com.palominocia.JooqProject.modelo.tables.OauthClientToken;
import com.palominocia.JooqProject.modelo.tables.OauthCode;
import com.palominocia.JooqProject.modelo.tables.OauthRefreshToken;
import com.palominocia.JooqProject.modelo.tables.Recursos;
import com.palominocia.JooqProject.modelo.tables.Roles;
import com.palominocia.JooqProject.modelo.tables.RolesGrupos;
import com.palominocia.JooqProject.modelo.tables.RolesUsuario;
import com.palominocia.JooqProject.modelo.tables.UsuarioTransaccion;
import com.palominocia.JooqProject.modelo.tables.Usuarios;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in autentificacion
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>autentificacion.CLIENTES</code>.
     */
    public static final Clientes CLIENTES = com.palominocia.JooqProject.modelo.tables.Clientes.CLIENTES;

    /**
     * The table <code>autentificacion.GRUPOS</code>.
     */
    public static final Grupos GRUPOS = com.palominocia.JooqProject.modelo.tables.Grupos.GRUPOS;

    /**
     * The table <code>autentificacion.GRUPO_RECURSOS</code>.
     */
    public static final GrupoRecursos GRUPO_RECURSOS = com.palominocia.JooqProject.modelo.tables.GrupoRecursos.GRUPO_RECURSOS;

    /**
     * The table <code>autentificacion.RECURSOS</code>.
     */
    public static final Recursos RECURSOS = com.palominocia.JooqProject.modelo.tables.Recursos.RECURSOS;

    /**
     * The table <code>autentificacion.ROLES</code>.
     */
    public static final Roles ROLES = com.palominocia.JooqProject.modelo.tables.Roles.ROLES;

    /**
     * The table <code>autentificacion.ROLES_GRUPOS</code>.
     */
    public static final RolesGrupos ROLES_GRUPOS = com.palominocia.JooqProject.modelo.tables.RolesGrupos.ROLES_GRUPOS;

    /**
     * The table <code>autentificacion.ROLES_USUARIO</code>.
     */
    public static final RolesUsuario ROLES_USUARIO = com.palominocia.JooqProject.modelo.tables.RolesUsuario.ROLES_USUARIO;

    /**
     * The table <code>autentificacion.USUARIOS</code>.
     */
    public static final Usuarios USUARIOS = com.palominocia.JooqProject.modelo.tables.Usuarios.USUARIOS;

    /**
     * The table <code>autentificacion.USUARIO_TRANSACCION</code>.
     */
    public static final UsuarioTransaccion USUARIO_TRANSACCION = com.palominocia.JooqProject.modelo.tables.UsuarioTransaccion.USUARIO_TRANSACCION;

    /**
     * The table <code>autentificacion.oauth_access_token</code>.
     */
    public static final OauthAccessToken OAUTH_ACCESS_TOKEN = com.palominocia.JooqProject.modelo.tables.OauthAccessToken.OAUTH_ACCESS_TOKEN;

    /**
     * The table <code>autentificacion.oauth_client_details</code>.
     */
    public static final OauthClientDetails OAUTH_CLIENT_DETAILS = com.palominocia.JooqProject.modelo.tables.OauthClientDetails.OAUTH_CLIENT_DETAILS;

    /**
     * The table <code>autentificacion.oauth_client_token</code>.
     */
    public static final OauthClientToken OAUTH_CLIENT_TOKEN = com.palominocia.JooqProject.modelo.tables.OauthClientToken.OAUTH_CLIENT_TOKEN;

    /**
     * The table <code>autentificacion.oauth_code</code>.
     */
    public static final OauthCode OAUTH_CODE = com.palominocia.JooqProject.modelo.tables.OauthCode.OAUTH_CODE;

    /**
     * The table <code>autentificacion.oauth_refresh_token</code>.
     */
    public static final OauthRefreshToken OAUTH_REFRESH_TOKEN = com.palominocia.JooqProject.modelo.tables.OauthRefreshToken.OAUTH_REFRESH_TOKEN;
}
