/*
 * This file is generated by jOOQ.
*/
package com.palominocia.JooqProject.modelo.tables.pojos;


import java.io.Serializable;
import java.sql.Date;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsuarioTransaccion implements Serializable {

    private static final long serialVersionUID = 1582970467;

    private Long   idTransaccion;
    private String direccionIp;
    private Date   fecUltimoLogin;
    private String idUsuario;

    public UsuarioTransaccion() {}

    public UsuarioTransaccion(UsuarioTransaccion value) {
        this.idTransaccion = value.idTransaccion;
        this.direccionIp = value.direccionIp;
        this.fecUltimoLogin = value.fecUltimoLogin;
        this.idUsuario = value.idUsuario;
    }

    public UsuarioTransaccion(
        Long   idTransaccion,
        String direccionIp,
        Date   fecUltimoLogin,
        String idUsuario
    ) {
        this.idTransaccion = idTransaccion;
        this.direccionIp = direccionIp;
        this.fecUltimoLogin = fecUltimoLogin;
        this.idUsuario = idUsuario;
    }

    public Long getIdTransaccion() {
        return this.idTransaccion;
    }

    public void setIdTransaccion(Long idTransaccion) {
        this.idTransaccion = idTransaccion;
    }

    public String getDireccionIp() {
        return this.direccionIp;
    }

    public void setDireccionIp(String direccionIp) {
        this.direccionIp = direccionIp;
    }

    public Date getFecUltimoLogin() {
        return this.fecUltimoLogin;
    }

    public void setFecUltimoLogin(Date fecUltimoLogin) {
        this.fecUltimoLogin = fecUltimoLogin;
    }

    public String getIdUsuario() {
        return this.idUsuario;
    }

    public void setIdUsuario(String idUsuario) {
        this.idUsuario = idUsuario;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UsuarioTransaccion (");

        sb.append(idTransaccion);
        sb.append(", ").append(direccionIp);
        sb.append(", ").append(fecUltimoLogin);
        sb.append(", ").append(idUsuario);

        sb.append(")");
        return sb.toString();
    }
}
