/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Modificar.java
 *
 * Created on 03/02/2011, 10:40:47 PM
 */
package registrador;

import Nodos.Direcciones;
import Nodos.ListaDobleConOrden;
import Nodos.NodoDoble;
import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.LimitExceededException;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;

/**
 *
 * @author JONATHAN
 */
public class Modificar extends javax.swing.JFrame{

    Connection enlace;
    Statement st = null;
    ResultSet resp = null;
    String url_consulta = "";
    DefaultListModel modelo = new DefaultListModel();
    int indice_planeta = 0;
    String direccion_planeta = "";
    public static ListaDobleConOrden lst = new ListaDobleConOrden();
    static Direcciones Direccion;
    public ArrayList contenido_planeta = new ArrayList();
    int nume_defensas = 0, nume_naves = 0, nume_tropas = 0;
    public JLabel[] etiketa;
    JTextField[] objetos_texto;
    String txtcodi_raza = "";
    private ArrayList tropas = new ArrayList();
    private ArrayList naves = new ArrayList();
    private ArrayList defensas = new ArrayList();

    /** Creates new form Modificar */
    Modificar(Libreria obje) {
        enlace = obje.getEnlace();
        initComponents();
        listDirecciones.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    public void EJECUTAR_MODIFICACION() {
        // TODO actualizar
        //Actualizar planetas
        Registrar_user_planetas(txtuser.getText().trim());
        //Actualizar unidades x planetas
        Modificar_unidades_planetas();
        // evita doble ejecucion
        btnConsulta.setEnabled(false);
        btnAgregar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnGuardarDatos.setEnabled(false);
        btnRealizar.setEnabled(false);
        menu_Cambios.setEnabled(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listDirecciones = new javax.swing.JList();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnGuardarDatos = new javax.swing.JButton();
        PanelPrincipal = new javax.swing.JTabbedPane();
        panel_tropas = new javax.swing.JPanel();
        Panel_naves = new javax.swing.JPanel();
        panel_defensas = new javax.swing.JPanel();
        txtRaza = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnRealizar = new javax.swing.JButton();
        btnConsulta = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menu_Cambios = new javax.swing.JMenuItem();
        Menu_salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar usuarios");

        jLabel1.setText("Usuario");

        jLabel3.setText("Direcciones");

        listDirecciones.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listDireccionesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listDirecciones);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnGuardarDatos.setText("GUARDAR DATOS  DE ESTA DIRECCION");
        btnGuardarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarDatosActionPerformed(evt);
            }
        });

        panel_tropas.setPreferredSize(new java.awt.Dimension(445, 378));

        javax.swing.GroupLayout panel_tropasLayout = new javax.swing.GroupLayout(panel_tropas);
        panel_tropas.setLayout(panel_tropasLayout);
        panel_tropasLayout.setHorizontalGroup(
            panel_tropasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 445, Short.MAX_VALUE)
        );
        panel_tropasLayout.setVerticalGroup(
            panel_tropasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );

        PanelPrincipal.addTab("Tropas", panel_tropas);

        javax.swing.GroupLayout Panel_navesLayout = new javax.swing.GroupLayout(Panel_naves);
        Panel_naves.setLayout(Panel_navesLayout);
        Panel_navesLayout.setHorizontalGroup(
            Panel_navesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 445, Short.MAX_VALUE)
        );
        Panel_navesLayout.setVerticalGroup(
            Panel_navesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );

        PanelPrincipal.addTab("Naves", Panel_naves);

        javax.swing.GroupLayout panel_defensasLayout = new javax.swing.GroupLayout(panel_defensas);
        panel_defensas.setLayout(panel_defensasLayout);
        panel_defensasLayout.setHorizontalGroup(
            panel_defensasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 445, Short.MAX_VALUE)
        );
        panel_defensasLayout.setVerticalGroup(
            panel_defensasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );

        PanelPrincipal.addTab("Defensas", panel_defensas);

        jLabel2.setText("Raza");

        btnRealizar.setText("Realizar cambios Totales");
        btnRealizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarActionPerformed(evt);
            }
        });

        btnConsulta.setText("Consultar");
        btnConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaActionPerformed(evt);
            }
        });

        jMenu1.setText("Otras opciones");

        menu_Cambios.setText("Realizar cambios Totales");
        menu_Cambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_CambiosActionPerformed(evt);
            }
        });
        jMenu1.add(menu_Cambios);

        Menu_salir.setText("Salir");
        Menu_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_salirActionPerformed(evt);
            }
        });
        jMenu1.add(Menu_salir);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(245, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtRaza, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnConsulta)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRealizar)
                .addContainerGap(326, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel3))
                    .addGap(48, 48, 48)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(29, 29, 29)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnGuardarDatos)
                                .addComponent(btnEliminar)
                                .addComponent(btnAgregar))))
                    .addContainerGap(18, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnConsulta))
                .addGap(129, 129, 129)
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRealizar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(22, 22, 22)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnAgregar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnEliminar)
                            .addGap(18, 18, 18)
                            .addComponent(btnGuardarDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addContainerGap(425, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listDireccionesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listDireccionesValueChanged
        //System.out.println(evt);
        if (evt.getValueIsAdjusting())//Para que solo imprima una sola vez
        {
            System.out.println("cambio de elemento");
            System.out.println(listDirecciones.getSelectedValue());
            indice_planeta = listDirecciones.getSelectedIndex();
            direccion_planeta = modelo.getElementAt(indice_planeta).toString();

            //Llamar Ed
            LLAMAR_VALORES_ED(listDirecciones.getSelectedValue().toString());
            //guardar datos de los paneles si estan con datos dependiendo de el item
            //cargar datos de los paneles con datos
        }
}//GEN-LAST:event_listDireccionesValueChanged

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        try {
            if (modelo.getSize() < 5) {
                String direccion = JOptionPane.showInputDialog("Ingrese direccion");
                if (!direccion.isEmpty() && DIRE_LIBRE(direccion)) {
                    modelo.addElement(direccion);

                    //Agregar estructura dinamica
                    contenido_planeta.add(direccion);//el planeta sera la cabecera
                    for (int i = 1; i < (nume_defensas + nume_naves + nume_tropas + 1); i++) {
                        contenido_planeta.add(0);//valor inicial de las unidades es 0
                    }
                    IngresaDatos(direccion, contenido_planeta);
                    lst.agrega(Direccion);
                }
                else {
                    return; //Regresa a la instruccion inicial
                }
            }
            else {
                System.out.println("acabo");
            }
            listDirecciones.setModel(modelo); //asignar el modelo
        }
        catch (NullPointerException nullPointerException) {
            JOptionPane.showMessageDialog(null, "Agrege algo a la direccion");
        }
}//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        System.out.println(modelo.getSize());

        try {
            NodoDoble auxiliar = lst.busca(listDirecciones.getSelectedValue().toString());
            if (auxiliar != null) {
                lst.elimina(auxiliar);
                //eliminar planeta en consulta
                url_consulta = "DELETE FROM Direcciones WHERE (Numero_direccion = '" + listDirecciones.getSelectedValue().toString() + "')";
                st = enlace.createStatement();
                st.execute(url_consulta);

                url_consulta = "DELETE FROM usuario_numero_tropas WHERE (numero_Direccion = '" + listDirecciones.getSelectedValue().toString() + "')";
                st.execute(url_consulta);

                url_consulta = "DELETE FROM usuario_numero_naves WHERE (numero_Direccion = '" + listDirecciones.getSelectedValue().toString() + "')";
                st.execute(url_consulta);

                url_consulta = "DELETE FROM usuario_numero_Defensas WHERE (numero_Direccion = '" + listDirecciones.getSelectedValue().toString() + "')";
                st.execute(url_consulta);
            }
            modelo.remove(listDirecciones.getSelectedIndex());

        }
        catch (Exception e) {
            System.out.println("vacio o sin seleccionar");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnGuardarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarDatosActionPerformed
        //modificar lista dinamica
        ACTUALIZA_VALORES_ED(listDirecciones.getSelectedValue().toString());
}//GEN-LAST:event_btnGuardarDatosActionPerformed

    private void btnConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaActionPerformed
        Limpiar_Lista();
        Limpiar_Paneles();
        Ejecucion();
        RECARGAR_TROPAS();
        RECARGAR_NAVES();
        RECARGAR_DEFENSAS();

    }//GEN-LAST:event_btnConsultaActionPerformed

    private void btnRealizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarActionPerformed
        EJECUTAR_MODIFICACION();
        lst.setInicio(null);
    }//GEN-LAST:event_btnRealizarActionPerformed

    private void Menu_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_salirActionPerformed
        dispose();
        lst.setInicio(null);
    }//GEN-LAST:event_Menu_salirActionPerformed

    private void menu_CambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_CambiosActionPerformed
        //Actualizar unidades x planetas
        EJECUTAR_MODIFICACION();
        lst.setInicio(null);
    }//GEN-LAST:event_menu_CambiosActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Menu_salir;
    private javax.swing.JTabbedPane PanelPrincipal;
    private javax.swing.JPanel Panel_naves;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnConsulta;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardarDatos;
    private javax.swing.JButton btnRealizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listDirecciones;
    private javax.swing.JMenuItem menu_Cambios;
    private javax.swing.JPanel panel_defensas;
    private javax.swing.JPanel panel_tropas;
    private javax.swing.JTextField txtRaza;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables

    public void Ejecucion() {
        boolean encontrado = false;
        int contador = 0;
        if (enlace != null) {
            try {
                url_consulta = "SELECT usuarios.nomb_usuarios,usuarios.codi_raza, Razas.nomb_raza FROM usuarios "
                        + "INNER JOIN Razas ON usuarios.codi_raza = Razas.codi_raza where"
                        + " usuarios.nomb_usuarios = '" + txtuser.getText().trim() + "'";
                st = enlace.createStatement();
                resp = st.executeQuery(url_consulta);
                while (resp.next()) {
                    // El metodo getObject llama a las columnas
                    //ya sea por su nombre o su indice de columna en este caso comensando en 1
                    txtRaza.setText(resp.getObject(3).toString());
                    txtcodi_raza = resp.getObject(2).toString();
                    if (resp.getObject(1).toString().equals(txtuser.getText().trim())) {
                        encontrado = true;
                    }
                }
                if (encontrado) {
                    url_consulta = "SELECT Numero_direccion, Galaxia,nomb_usuarios"
                            + " FROM Direcciones where nomb_usuarios = '" + txtuser.getText().trim() + "'";
                    resp = st.executeQuery(url_consulta);
                    while (resp.next()) {
                        Agregar_Lista(resp.getObject(1).toString());
                        contador++;
                    }
                    listDirecciones.setModel(modelo);
                    for (int i = 0; i < contador; i++) {
                        EJECUTAR_ELEMENTOS(modelo.get(i).toString());
                        System.out.println(modelo.get(i).toString());
                    }
                    //Existe el elemento entonces se puede eliminar
                }
                else {
                    JOptionPane.showMessageDialog(null, "No se hallo la consulta", "Resultado", JOptionPane.INFORMATION_MESSAGE);
                }

            }
            catch (SQLException ex) {
                System.out.println("Error");
                Logger.getLogger(Agregar.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }

    private void EJECUTAR_ELEMENTOS(String txtdireccion) {
        ArrayList temporal = new ArrayList();
        temporal.add(txtdireccion);
        try {
            url_consulta = "SELECT cantidad_trop, numero_Direccion FROM usuario_numero_tropas "
                    + "WHERE (numero_Direccion = '" + txtdireccion + "')";
            st = enlace.createStatement();
            resp = st.executeQuery(url_consulta);
            while (resp.next()) {
                temporal.add(resp.getObject(1));
            }

            url_consulta = "SELECT cantidad_nav, numero_Direccion FROM usuario_numero_naves "
                    + "WHERE (numero_Direccion = '" + txtdireccion + "')";
            resp = st.executeQuery(url_consulta);
            while (resp.next()) {
                temporal.add(resp.getObject(1));
            }

            url_consulta = "SELECT cantidad_def, numero_Direccion FROM usuario_numero_Defensas "
                    + "WHERE (numero_Direccion = '" + txtdireccion + "')";
            resp = st.executeQuery(url_consulta);
            while (resp.next()) {
                temporal.add(resp.getObject(1));
            }
            IngresaDatos(txtdireccion, temporal);
            lst.agrega(Direccion);
        }
        catch (SQLException ex) {
            Logger.getLogger(Modificar.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void Agregar_Lista(String direccion) {
        //System.out.println(direccion);
        modelo.addElement(direccion);
    }

    private void IngresaDatos(String direccion, ArrayList contenido_planeta) {
        Direccion = new Direcciones();
        Direccion.setContenido(contenido_planeta);
        Direccion.setNombre(direccion);
    }

    private void ACTUALIZA_VALORES_ED(String toString) {
        ArrayList temporal = new ArrayList();
        System.out.println("Direccion actual " + toString);
        temporal.add(toString);
        //LLAMAR ED
        for (int i = 0; i < nume_tropas; i++) {
            String valor_caja_texto = ((JTextField) panel_tropas.getComponent(i * 2 + 1)).getText().trim();//txt del panel tropas
            //System.out.println("tropas " + valor_caja_texto);
            temporal.add(valor_caja_texto);
        }
        for (int i = 0; i < nume_naves; i++) {
            String valor_caja_texto = ((JTextField) Panel_naves.getComponent(i * 2 + 1)).getText().trim();//txt del panel tropas
            //System.out.println("naves " + valor_caja_texto);
            temporal.add(valor_caja_texto);
        }
        for (int i = 0; i < (nume_defensas); i++) {
            String valor_caja_texto = ((JTextField) panel_defensas.getComponent(i * 2 + 1)).getText().trim();//txt del panel tropas
            //System.out.println("defensas " + valor_caja_texto);
            temporal.add(valor_caja_texto);
        }
        //busca el dato para actualizar valores
        NodoDoble auxiliar = lst.busca(toString);
        if (auxiliar != null) { // no lo encontró
            Direccion = auxiliar.getNodo();
            Direccion.setContenido(temporal);
            System.out.println("Direccion " + Direccion.getNombre());
            for (int i = 1; i < temporal.size(); i++) {
                System.out.println("valores cargados " + temporal.get(i));
            }
        }
        //Guarda informacion de paneles
    }

    private void LLAMAR_VALORES_ED(String toString) {
        NodoDoble auxiliar = lst.busca(toString);
        ArrayList temporal = new ArrayList();
        if (auxiliar != null) {
            Direccion = auxiliar.getNodo();
            temporal = Direccion.getContenido();

            for (int i = 0; i < nume_tropas; i++) {
                String valor_caja_texto = temporal.get(i + 1).toString();
                ((JTextField) panel_tropas.getComponent(i * 2 + 1)).setText(valor_caja_texto);
            }
            for (int i = 0; i < nume_naves; i++) {
                String valor_caja_texto = temporal.get(i + nume_tropas + 1).toString();//txt del panel tropas
                ((JTextField) Panel_naves.getComponent(i * 2 + 1)).setText(valor_caja_texto);
            }
            for (int i = 0; i < nume_defensas; i++) {
                String valor_caja_texto = temporal.get(i + nume_tropas + nume_naves + 1).toString();//txt del panel tropas
                ((JTextField) panel_defensas.getComponent(i * 2 + 1)).setText(valor_caja_texto);
            }
        }

    }

    private void RECARGAR_TROPAS() {
        if (enlace != null) {
            try {
                url_consulta = "select * from Tropas where codi_raza = '" + txtcodi_raza + "'";
                st = enlace.createStatement();
                ResultSet resp1 = st.executeQuery(url_consulta);
                int alto_panel = panel_tropas.getHeight(); //obtener alto
                ArrayList lista = new ArrayList();
                while (resp1.next()) {
                    //System.out.println(resp1.getObject(1));
                    lista.add(resp1.getObject(1));
                }
                nume_tropas = lista.size();
                setTropas(lista);
                int espaciado = (int) (alto_panel / lista.size()) + 1;
                Crear_Objetos(espaciado, panel_tropas, lista);
                //Ahora pintar las tropas
            }
            catch (SQLException ex) {
                Logger.getLogger(Agregar.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    private void RECARGAR_NAVES() {
        if (enlace != null) {
            try {
                url_consulta = "select * from Naves where codi_raza = '" + txtcodi_raza + "'";
                st = enlace.createStatement();
                ResultSet resp = st.executeQuery(url_consulta);
                int alto_panel = panel_tropas.getHeight(); //obtener alto
                ArrayList lista = new ArrayList();
                while (resp.next()) {
                    //System.out.println(resp.getObject(1));
                    lista.add(resp.getObject(1));
                }
                nume_naves = lista.size();
                setNaves(lista);
                int espaciado = (int) (alto_panel / lista.size()) + 1;
                Crear_Objetos(espaciado, Panel_naves, lista);
            }
            catch (SQLException ex) {
                Logger.getLogger(Consulta.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    private void RECARGAR_DEFENSAS() {
        if (enlace != null) {
            try {
                url_consulta = "select * from Defensas where codi_raza = '" + txtcodi_raza + "'";
                st = enlace.createStatement();
                ResultSet resp = st.executeQuery(url_consulta);
                int alto_panel = panel_tropas.getHeight(); //obtener alto
                ArrayList lista = new ArrayList();
                while (resp.next()) {
                    //System.out.println(resp.getObject(1));
                    lista.add(resp.getObject(1));
                }
                nume_defensas = lista.size();
                setDefensas(lista);
                int espaciado = (int) (alto_panel / lista.size()) + 1;
                Crear_Objetos(espaciado, panel_defensas, lista);
            }
            catch (SQLException ex) {
                Logger.getLogger(Consulta.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    private void Crear_Objetos(int espaciado, JPanel panel_padre, ArrayList lista) {
        etiketa = new JLabel[lista.size()];
        objetos_texto = new JTextField[espaciado];
        for (int i = 0; i < lista.size(); i++) {
            etiketa[i] = new JLabel(lista.get(i).toString());
            panel_padre.add(etiketa[i]);
            objetos_texto[i] = new JTextField("");
            panel_padre.add(objetos_texto[i]);
            objetos_texto[i].setText("");
            objetos_texto[i].setBounds(300, 20 + espaciado * i, 50, 20);
            etiketa[i].setBounds(20, 20 + espaciado * i, 150, 20);
        }
    }

    private void Modificar_unidades_planetas() {
        try {
            String direccion_actual = listDirecciones.getSelectedValue().toString();
            System.out.println(direccion_actual);
            String usuario = txtuser.getText().trim();
            //hacer consulta
            //llamar nombre de usuario
            //llamar cada direccion en la ED
            NodoDoble auxiliar = lst.getInicio();
            while (auxiliar != null) {
                ArrayList temp = auxiliar.getNodo().getContenido();
                if (BUSCAREXISTENCIA(temp.get(0).toString())) {
                    //Si existe actualizar
                    for (int i = 1; i < temp.size(); i++) {
                        if (i <= getTropas().size()) {
                            try {
                                url_consulta = "UPDATE `usuario_numero_tropas` SET `cantidad_trop` = '" + temp.get(i) + "' WHERE `nomb_usuarios` = '" + usuario + "' AND `numero_Direccion` = '" + temp.get(0) + "' AND `nomb_tropas` = '" + ((JLabel) panel_tropas.getComponent((i - 1) * 2)).getText().trim() + "'";
                                System.out.println(url_consulta);
                                st = enlace.createStatement();
                                st.execute(url_consulta);
                            }
                            catch (SQLException ex) {
                                //
                            }
                        }
                        else if (i > getTropas().size() && i <= (getNaves().size() + getTropas().size())) {
                            try {
                                url_consulta = "UPDATE `usuario_numero_naves` SET `cantidad_nav` = '" + temp.get(i) + "' WHERE `nomb_usuarios` = '" + usuario + "' AND `Nomb_Naves` = '" + ((JLabel) Panel_naves.getComponent((i - 1 - getTropas().size()) * 2)).getText().trim() + "' AND `numero_Direccion` = '" + temp.get(0) + "'";
                                System.out.println(url_consulta);
                                st = enlace.createStatement();
                                st.execute(url_consulta);
                            }
                            catch (SQLException ex) {
                                //
                            }
                        }
                        else if (i > (getNaves().size() + getTropas().size())) {
                            try {
                                url_consulta = "UPDATE `usuario_numero_Defensas` SET `cantidad_def` = '" + temp.get(i) + "' WHERE `nomb_usuarios` = '" + usuario + "' AND `nomb_Defensas` = '" + ((JLabel) panel_defensas.getComponent((i - 1 - getTropas().size() - getNaves().size()) * 2)).getText().trim() + "' AND `numero_Direccion` = '" + temp.get(0) + "'";
                                System.out.println(url_consulta);
                                st = enlace.createStatement();
                                st.execute(url_consulta);
                            }
                            catch (SQLException ex) {
                                //
                            }
                        }
                    }
                }
                else {
                    //Si no existe insertar
                    for (int i = 1; i < temp.size(); i++) {
                        if (i <= getTropas().size()) {
                            try {
                                url_consulta = "INSERT INTO usuario_numero_tropas " + "(nomb_usuarios, nomb_tropas, cantidad_trop, numero_Direccion) " + "VALUES ('" + usuario + "', '" + ((JLabel) panel_tropas.getComponent((i - 1) * 2)).getText().trim() + "', '" + temp.get(i) + "', '" + temp.get(0) + "')";
                                System.out.println(url_consulta);
                                st = enlace.createStatement();
                                st.execute(url_consulta);
                            }
                            catch (SQLException ex) {
                                //
                            }
                        }
                        else if (i > getTropas().size() && i <= (getNaves().size() + getTropas().size())) {
                            try {
                                url_consulta = "INSERT INTO usuario_numero_naves " + "(nomb_usuarios, Nomb_Naves, cantidad_nav, numero_Direccion) " + "VALUES ('" + usuario + "', '" + ((JLabel) Panel_naves.getComponent((i - 1 - getTropas().size()) * 2)).getText().trim() + "', '" + temp.get(i) + "', '" + temp.get(0) + "')";
                                System.out.println(url_consulta);
                                st = enlace.createStatement();
                                st.execute(url_consulta);
                            }
                            catch (SQLException ex) {
                                //
                            }
                        }
                        else if (i > (getNaves().size() + getTropas().size())) {
                            try {
                                url_consulta = "INSERT INTO usuario_numero_Defensas " + "(nomb_usuarios, nomb_Defensas, cantidad_def, numero_Direccion) " + "VALUES ('" + usuario + "', '" + ((JLabel) panel_defensas.getComponent((i - 1 - getTropas().size() - getNaves().size()) * 2)).getText().trim() + "', '" + temp.get(i) + "', '" + temp.get(0) + "')";
                                System.out.println(url_consulta);
                                st = enlace.createStatement();
                                st.execute(url_consulta);
                            }
                            catch (SQLException ex) {
                                //
                            }
                        }
                    }
                }

                auxiliar = auxiliar.getApuntSgte();
            }
            //por cada direccion hacer una consulta de insert
        }
        catch (Exception e) {
            //error
        }

    }

    private void Registrar_user_planetas(String usuario) {
        if (enlace != null) {
            for (int i = 0; i < modelo.getSize(); i++) {
                try {
                    System.out.println(modelo.getElementAt(i)); //LISTAR PLANETAS
                    url_consulta = "INSERT INTO Direcciones (Numero_direccion, Galaxia, nomb_usuarios) VALUES ('" + modelo.getElementAt(i).toString() + "', '" + Deducir_galaxia(modelo.getElementAt(i).toString()) + "', '" + usuario + "')";
                    st = enlace.createStatement();
                    st.execute(url_consulta);
                }
                catch (SQLException ex) {
                }
            }
        }
    }

    private String Deducir_galaxia(String direccion) {
        String nombre_galaxia = "";
        char primeraletra = direccion.charAt(0);
        if (primeraletra == "P".charAt(0)) {
            nombre_galaxia = "Pegasus";
            System.out.println("Pegasus");
        }
        else if (primeraletra == "A".charAt(0)) {
            System.out.println("Andromeda");
            nombre_galaxia = "Andrómeda";
        }
        else if (primeraletra == "M".charAt(0)) {
            System.out.println("Midguay");
            nombre_galaxia = "Midway";
        }
        else if (primeraletra == "V".charAt(0)) {
            System.out.println("Via Lactea");
            nombre_galaxia = "Vía Láctea";
        }
        return nombre_galaxia;
    }

    /**
     * @return the tropas
     */
    public ArrayList getTropas() {
        return tropas;
    }

    /**
     * @param tropas the tropas to set
     */
    public void setTropas(ArrayList tropas) {
        this.tropas = tropas;
    }

    /**
     * @return the naves
     */
    public ArrayList getNaves() {
        return naves;
    }

    /**
     * @param naves the naves to set
     */
    public void setNaves(ArrayList naves) {
        this.naves = naves;
    }

    /**
     * @return the defensas
     */
    public ArrayList getDefensas() {
        return defensas;
    }

    /**
     * @param defensas the defensas to set
     */
    public void setDefensas(ArrayList defensas) {
        this.defensas = defensas;
    }

    private boolean BUSCAREXISTENCIA(String direccion) {
        boolean existencia = false;
        try {
            //buscar si existe la direccion en una tabla;
            String url = "select * from `usuario_numero_Defensas` where numero_Direccion = '" + direccion + "'";
            st = enlace.createStatement();
            resp = st.executeQuery(url);
            while (resp.next()) {
                existencia = true;
            }
        }
        catch (SQLException ex) {
            Logger.getLogger(Modificar.class.getName()).log(Level.SEVERE, null, ex);
        }
        return existencia;
    }

    private boolean DIRE_LIBRE(String direccion) {
        boolean retorno = true;
        try {

            url_consulta = "select Numero_direccion from Direcciones where Numero_direccion='" + direccion + "'";
            st = enlace.createStatement();
            resp = st.executeQuery(url_consulta);
            while (resp.next()) {
                retorno = false;
            }

        }
        catch (SQLException ex) {
            Logger.getLogger(Agregar.class.getName()).log(Level.SEVERE, null, ex);
        }
        return retorno;
    }

    private void Limpiar_Paneles() {
        panel_tropas.removeAll();
        panel_tropas.repaint();
        Panel_naves.removeAll();
        Panel_naves.repaint();
        panel_defensas.removeAll();
        panel_defensas.repaint();
    }

    private void Limpiar_Lista() {
        modelo.clear();
        listDirecciones.setModel(modelo);
        listDirecciones.clearSelection();
    }
}
