/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * numerosgrafico.java
 *
 * Created on 13/05/2009, 06:52:10 PM
 */

package problemasunfv;

/**
 *
 * @author JONATHAN
 */
public class numerosgrafico extends javax.swing.JFrame {
int contador=0;
String cadena = "Los gerenados son: ",cadena1="Los que concuerdan son: ";
    /** Creates new form numerosgrafico */
    public numerosgrafico() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Calcular = new javax.swing.JButton();
        txta = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtRespuesta = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Escribir cantidad de números");

        Calcular.setText("Calcular");
        Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularActionPerformed(evt);
            }
        });

        txta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txta.setText("0");

        txtRespuesta.setColumns(20);
        txtRespuesta.setRows(5);
        jScrollPane1.setViewportView(txtRespuesta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txta, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(Calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularActionPerformed
       int a;
       try {
            a = Integer.parseInt( txta.getText() );
        }
        catch (java.lang.NumberFormatException e){
            txtRespuesta.setText("Ingrese un número entero");
            // Dar el foco al control
            txta.grabFocus();
            return; // Retorna si ejecutar las líneas de abajo
        }
       //Validar datos
       if (a <= 0) {
            txtRespuesta.setText("debe ser mayor que 0");
            txta.grabFocus();
            return;
        }
        
        // Calculando la respuesta
       numero(a);
        txtRespuesta.setText(cadena+"\n"+cadena1);
    }//GEN-LAST:event_CalcularActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new numerosgrafico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Calcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtRespuesta;
    private javax.swing.JTextField txta;
    // End of variables declaration//GEN-END:variables

    private void numero(int externo)
    {
        int inicial = 0,d = 0,d1,temporal=0;
        while(inicial<externo)
        {
            d=(int)(Math.random()*1000);
            System.out.println(d);
            cadena = cadena+"\n"+d;
                int r=1;
                temporal=d;
                d1=temporal%10;
                while (d!=0)
                {
                    r=d%10;
                    d=d/10;
                 }
                if (r==d1)
                {
                    //System.out.println("Si cumple la condicion"); 
                    contador++;
                }
                else
                {
                    //System.out.println("No cumple la condicion");
                }
          inicial++;
        }
        cadena1 = cadena1+String.valueOf(contador);
    }
}
