/*
 * This file is generated by jOOQ.
*/
package com.palominocia.JooqProject.modelo.tables.records;


import com.palominocia.JooqProject.modelo.tables.OauthCode;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OauthCodeRecord extends TableRecordImpl<OauthCodeRecord> implements Record2<String, byte[]> {

    private static final long serialVersionUID = 1002254452;

    /**
     * Setter for <code>autentificacion.oauth_code.error</code>.
     */
    public void setError(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>autentificacion.oauth_code.error</code>.
     */
    public String getError() {
        return (String) get(0);
    }

    /**
     * Setter for <code>autentificacion.oauth_code.authentication</code>.
     */
    public void setAuthentication(byte... value) {
        set(1, value);
    }

    /**
     * Getter for <code>autentificacion.oauth_code.authentication</code>.
     */
    public byte[] getAuthentication() {
        return (byte[]) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, byte[]> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, byte[]> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return OauthCode.OAUTH_CODE.ERROR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field2() {
        return OauthCode.OAUTH_CODE.AUTHENTICATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getError();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] component2() {
        return getAuthentication();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getError();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value2() {
        return getAuthentication();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OauthCodeRecord value1(String value) {
        setError(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OauthCodeRecord value2(byte... value) {
        setAuthentication(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OauthCodeRecord values(String value1, byte[] value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OauthCodeRecord
     */
    public OauthCodeRecord() {
        super(OauthCode.OAUTH_CODE);
    }

    /**
     * Create a detached, initialised OauthCodeRecord
     */
    public OauthCodeRecord(String error, byte[] authentication) {
        super(OauthCode.OAUTH_CODE);

        set(0, error);
        set(1, authentication);
    }
}
