/*
 * This file is generated by jOOQ.
*/
package com.palominocia.JooqProject.modelo.tables.records;


import com.palominocia.JooqProject.modelo.tables.RolesUsuario;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RolesUsuarioRecord extends UpdatableRecordImpl<RolesUsuarioRecord> implements Record2<String, Long> {

    private static final long serialVersionUID = -974379935;

    /**
     * Setter for <code>autentificacion.ROLES_USUARIO.ID_USUARIO</code>.
     */
    public void setIdUsuario(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>autentificacion.ROLES_USUARIO.ID_USUARIO</code>.
     */
    public String getIdUsuario() {
        return (String) get(0);
    }

    /**
     * Setter for <code>autentificacion.ROLES_USUARIO.ID_ROL</code>.
     */
    public void setIdRol(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>autentificacion.ROLES_USUARIO.ID_ROL</code>.
     */
    public Long getIdRol() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<String, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return RolesUsuario.ROLES_USUARIO.ID_USUARIO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return RolesUsuario.ROLES_USUARIO.ID_ROL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getIdUsuario();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getIdRol();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getIdUsuario();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getIdRol();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RolesUsuarioRecord value1(String value) {
        setIdUsuario(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RolesUsuarioRecord value2(Long value) {
        setIdRol(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RolesUsuarioRecord values(String value1, Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RolesUsuarioRecord
     */
    public RolesUsuarioRecord() {
        super(RolesUsuario.ROLES_USUARIO);
    }

    /**
     * Create a detached, initialised RolesUsuarioRecord
     */
    public RolesUsuarioRecord(String idUsuario, Long idRol) {
        super(RolesUsuario.ROLES_USUARIO);

        set(0, idUsuario);
        set(1, idRol);
    }
}
