/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Princ.java
 *
 * Created on 17/08/2011, 10:38:17 PM
 */
/**
 *
 * @author Jonathan palomino <jhonelfenix@gmail.com>
 */
public class Princ extends javax.swing.JFrame {
Secu obj;
    /** Creates new form Princ */
    public Princ() {
        obj=new Secu();
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CMB_USB = new javax.swing.JCheckBox();
        txt_usb = new javax.swing.JTextField();
        txt_Total = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CMB_USB.setText("Memoria USB");
        CMB_USB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                CMB_USBStateChanged(evt);
            }
        });

        txt_usb.setText("jTextField1");

        txt_Total.setText("jTextField2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(CMB_USB)
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_usb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CMB_USB)
                    .addComponent(txt_usb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92)
                .addComponent(txt_Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CMB_USBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_CMB_USBStateChanged
        if(CMB_USB.isSelected()){
            txt_usb.setText("40");
            obj.P1=Double.parseDouble(txt_usb.getText());
        }
        else{
          txt_usb.setText("0");  
          obj.P1=Double.parseDouble(txt_usb.getText());
        }
        Calcular_Total();
    }//GEN-LAST:event_CMB_USBStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Princ().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CMB_USB;
    private javax.swing.JTextField txt_Total;
    private javax.swing.JTextField txt_usb;
    // End of variables declaration//GEN-END:variables

    private void Calcular_Total() {
        txt_Total.setText(String.valueOf(obj.P1)); ///Esta es una forma
        //txt_Total.setText(String.valueOf(obj.sumar())); ///Esta es otra forma 
    }
}
