/*
 * This file is generated by jOOQ.
*/
package com.palominocia.JooqProject.modelo.tables;


import com.palominocia.JooqProject.modelo.Autentificacion;
import com.palominocia.JooqProject.modelo.Keys;
import com.palominocia.JooqProject.modelo.tables.records.UsuariosRecord;

import java.sql.Date;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Usuarios extends TableImpl<UsuariosRecord> {

    private static final long serialVersionUID = -1596497932;

    /**
     * The reference instance of <code>autentificacion.USUARIOS</code>
     */
    public static final Usuarios USUARIOS = new Usuarios();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UsuariosRecord> getRecordType() {
        return UsuariosRecord.class;
    }

    /**
     * The column <code>autentificacion.USUARIOS.ID_USUARIO</code>.
     */
    public final TableField<UsuariosRecord, String> ID_USUARIO = createField("ID_USUARIO", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>autentificacion.USUARIOS.NOMBRE</code>.
     */
    public final TableField<UsuariosRecord, String> NOMBRE = createField("NOMBRE", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>autentificacion.USUARIOS.PASSWORD</code>.
     */
    public final TableField<UsuariosRecord, String> PASSWORD = createField("PASSWORD", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>autentificacion.USUARIOS.DESCRIPCION</code>.
     */
    public final TableField<UsuariosRecord, String> DESCRIPCION = createField("DESCRIPCION", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>autentificacion.USUARIOS.MCA_HABILITADO</code>.
     */
    public final TableField<UsuariosRecord, String> MCA_HABILITADO = createField("MCA_HABILITADO", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>autentificacion.USUARIOS.FEC_ACTU</code>.
     */
    public final TableField<UsuariosRecord, Date> FEC_ACTU = createField("FEC_ACTU", org.jooq.impl.SQLDataType.DATE, this, "");

    /**
     * The column <code>autentificacion.USUARIOS.ID_USUARIO_MODIF</code>.
     */
    public final TableField<UsuariosRecord, String> ID_USUARIO_MODIF = createField("ID_USUARIO_MODIF", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>autentificacion.USUARIOS</code> table reference
     */
    public Usuarios() {
        this(DSL.name("USUARIOS"), null);
    }

    /**
     * Create an aliased <code>autentificacion.USUARIOS</code> table reference
     */
    public Usuarios(String alias) {
        this(DSL.name(alias), USUARIOS);
    }

    /**
     * Create an aliased <code>autentificacion.USUARIOS</code> table reference
     */
    public Usuarios(Name alias) {
        this(alias, USUARIOS);
    }

    private Usuarios(Name alias, Table<UsuariosRecord> aliased) {
        this(alias, aliased, null);
    }

    private Usuarios(Name alias, Table<UsuariosRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Autentificacion.AUTENTIFICACION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<UsuariosRecord> getPrimaryKey() {
        return Keys.USUARIO_PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<UsuariosRecord>> getKeys() {
        return Arrays.<UniqueKey<UsuariosRecord>>asList(Keys.USUARIO_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<UsuariosRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<UsuariosRecord, ?>>asList(Keys.USUARIOS__FK_ID_USUARIO_USUARIOS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Usuarios as(String alias) {
        return new Usuarios(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Usuarios as(Name alias) {
        return new Usuarios(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Usuarios rename(String name) {
        return new Usuarios(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Usuarios rename(Name name) {
        return new Usuarios(name, null);
    }
}
