/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on 02/05/2011, 09:45:15 PM
 */
package algo_julio_cesar;

/**
 *
 * @author JONATHAN
 */
public class NewJFrame extends javax.swing.JFrame{

    cesar cesar;
    Bifido b;

    /** Creates new form NewJFrame */
    public NewJFrame() {
        initComponents();
        cesar = new cesar();
        b = new Bifido();
    }

    public void Visi(boolean Visi) {
        txtIntervalo.setVisible(Visi);
        label.setVisible(Visi);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        Inicial = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        Final = new javax.swing.JTextArea();
        btnEncriptar = new javax.swing.JButton();
        btnDesencriptar = new javax.swing.JButton();
        label = new javax.swing.JLabel();
        txtIntervalo = new javax.swing.JTextField();
        RBJulio = new javax.swing.JRadioButton();
        RBBifi = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Encriptar");

        Inicial.setColumns(20);
        Inicial.setRows(5);
        jScrollPane1.setViewportView(Inicial);

        Final.setColumns(20);
        Final.setRows(5);
        jScrollPane2.setViewportView(Final);

        btnEncriptar.setText("Encriptar");
        btnEncriptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncriptarActionPerformed(evt);
            }
        });

        btnDesencriptar.setText("Desencriptar");
        btnDesencriptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesencriptarActionPerformed(evt);
            }
        });

        label.setText("Intervalo");

        buttonGroup1.add(RBJulio);
        RBJulio.setSelected(true);
        RBJulio.setText("Julio Cesar");
        RBJulio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBJulioActionPerformed(evt);
            }
        });

        buttonGroup1.add(RBBifi);
        RBBifi.setText("Bifido");
        RBBifi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBBifiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEncriptar)
                                .addGap(37, 37, 37)
                                .addComponent(btnDesencriptar)
                                .addGap(57, 57, 57)
                                .addComponent(label)
                                .addGap(28, 28, 28)
                                .addComponent(txtIntervalo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(87, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RBJulio)
                            .addComponent(RBBifi))
                        .addGap(36, 36, 36))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEncriptar)
                    .addComponent(btnDesencriptar)
                    .addComponent(label)
                    .addComponent(txtIntervalo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(RBJulio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RBBifi)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEncriptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncriptarActionPerformed
        if (RBJulio.isSelected()) {
            String texto_inicial = Inicial.getText();
            int intervalo = Integer.parseInt(txtIntervalo.getText());
            if (intervalo <= 10) {
                Final.setText(cesar.Encriptar(texto_inicial, intervalo));
            }
        }
        else {
            String t = Inicial.getText();
            Final.setText(b.Encriptar(t));
        }

    }//GEN-LAST:event_btnEncriptarActionPerformed

    private void btnDesencriptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesencriptarActionPerformed
        if (RBJulio.isSelected()) {
            String texto_inicial = Inicial.getText();
            int intervalo = Integer.parseInt(txtIntervalo.getText());
            if (intervalo <= 10) {
                Final.setText(cesar.Desencriptar(texto_inicial, intervalo));
            }
        }
        else {
            String t = Inicial.getText();
            Final.setText(b.Desencriptar(t));
        }
    }//GEN-LAST:event_btnDesencriptarActionPerformed

    private void RBBifiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBBifiActionPerformed
        Visi(false);
    }//GEN-LAST:event_RBBifiActionPerformed

    private void RBJulioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBJulioActionPerformed
        Visi(true);
    }//GEN-LAST:event_RBJulioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable(){

            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Final;
    private javax.swing.JTextArea Inicial;
    private javax.swing.JRadioButton RBBifi;
    private javax.swing.JRadioButton RBJulio;
    private javax.swing.JButton btnDesencriptar;
    private javax.swing.JButton btnEncriptar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label;
    private javax.swing.JTextField txtIntervalo;
    // End of variables declaration//GEN-END:variables
}
