/*
 * This file is generated by jOOQ.
*/
package com.palominocia.JooqProject.modelo.tables.pojos;


import java.io.Serializable;
import java.sql.Date;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Clientes implements Serializable {

    private static final long serialVersionUID = -1169543094;

    private Long    idCliente;
    private Integer accessTokenValiditySecondsAlias;
    private String  additionalInformationStr;
    private String  authoritiesStr;
    private String  authorizedGrantTypeStr;
    private String  clientIdAlias;
    private String  clientSecretAlias;
    private String  publicKey;
    private Integer refreshTokenValiditySecondsAlias;
    private String  registeredRedirectUriStr;
    private String  resourceIdStr;
    private String  scopeStr;
    private String  mcaHabilitado;
    private Date    fecActu;
    private String  idUsuarioModif;

    public Clientes() {}

    public Clientes(Clientes value) {
        this.idCliente = value.idCliente;
        this.accessTokenValiditySecondsAlias = value.accessTokenValiditySecondsAlias;
        this.additionalInformationStr = value.additionalInformationStr;
        this.authoritiesStr = value.authoritiesStr;
        this.authorizedGrantTypeStr = value.authorizedGrantTypeStr;
        this.clientIdAlias = value.clientIdAlias;
        this.clientSecretAlias = value.clientSecretAlias;
        this.publicKey = value.publicKey;
        this.refreshTokenValiditySecondsAlias = value.refreshTokenValiditySecondsAlias;
        this.registeredRedirectUriStr = value.registeredRedirectUriStr;
        this.resourceIdStr = value.resourceIdStr;
        this.scopeStr = value.scopeStr;
        this.mcaHabilitado = value.mcaHabilitado;
        this.fecActu = value.fecActu;
        this.idUsuarioModif = value.idUsuarioModif;
    }

    public Clientes(
        Long    idCliente,
        Integer accessTokenValiditySecondsAlias,
        String  additionalInformationStr,
        String  authoritiesStr,
        String  authorizedGrantTypeStr,
        String  clientIdAlias,
        String  clientSecretAlias,
        String  publicKey,
        Integer refreshTokenValiditySecondsAlias,
        String  registeredRedirectUriStr,
        String  resourceIdStr,
        String  scopeStr,
        String  mcaHabilitado,
        Date    fecActu,
        String  idUsuarioModif
    ) {
        this.idCliente = idCliente;
        this.accessTokenValiditySecondsAlias = accessTokenValiditySecondsAlias;
        this.additionalInformationStr = additionalInformationStr;
        this.authoritiesStr = authoritiesStr;
        this.authorizedGrantTypeStr = authorizedGrantTypeStr;
        this.clientIdAlias = clientIdAlias;
        this.clientSecretAlias = clientSecretAlias;
        this.publicKey = publicKey;
        this.refreshTokenValiditySecondsAlias = refreshTokenValiditySecondsAlias;
        this.registeredRedirectUriStr = registeredRedirectUriStr;
        this.resourceIdStr = resourceIdStr;
        this.scopeStr = scopeStr;
        this.mcaHabilitado = mcaHabilitado;
        this.fecActu = fecActu;
        this.idUsuarioModif = idUsuarioModif;
    }

    public Long getIdCliente() {
        return this.idCliente;
    }

    public void setIdCliente(Long idCliente) {
        this.idCliente = idCliente;
    }

    public Integer getAccessTokenValiditySecondsAlias() {
        return this.accessTokenValiditySecondsAlias;
    }

    public void setAccessTokenValiditySecondsAlias(Integer accessTokenValiditySecondsAlias) {
        this.accessTokenValiditySecondsAlias = accessTokenValiditySecondsAlias;
    }

    public String getAdditionalInformationStr() {
        return this.additionalInformationStr;
    }

    public void setAdditionalInformationStr(String additionalInformationStr) {
        this.additionalInformationStr = additionalInformationStr;
    }

    public String getAuthoritiesStr() {
        return this.authoritiesStr;
    }

    public void setAuthoritiesStr(String authoritiesStr) {
        this.authoritiesStr = authoritiesStr;
    }

    public String getAuthorizedGrantTypeStr() {
        return this.authorizedGrantTypeStr;
    }

    public void setAuthorizedGrantTypeStr(String authorizedGrantTypeStr) {
        this.authorizedGrantTypeStr = authorizedGrantTypeStr;
    }

    public String getClientIdAlias() {
        return this.clientIdAlias;
    }

    public void setClientIdAlias(String clientIdAlias) {
        this.clientIdAlias = clientIdAlias;
    }

    public String getClientSecretAlias() {
        return this.clientSecretAlias;
    }

    public void setClientSecretAlias(String clientSecretAlias) {
        this.clientSecretAlias = clientSecretAlias;
    }

    public String getPublicKey() {
        return this.publicKey;
    }

    public void setPublicKey(String publicKey) {
        this.publicKey = publicKey;
    }

    public Integer getRefreshTokenValiditySecondsAlias() {
        return this.refreshTokenValiditySecondsAlias;
    }

    public void setRefreshTokenValiditySecondsAlias(Integer refreshTokenValiditySecondsAlias) {
        this.refreshTokenValiditySecondsAlias = refreshTokenValiditySecondsAlias;
    }

    public String getRegisteredRedirectUriStr() {
        return this.registeredRedirectUriStr;
    }

    public void setRegisteredRedirectUriStr(String registeredRedirectUriStr) {
        this.registeredRedirectUriStr = registeredRedirectUriStr;
    }

    public String getResourceIdStr() {
        return this.resourceIdStr;
    }

    public void setResourceIdStr(String resourceIdStr) {
        this.resourceIdStr = resourceIdStr;
    }

    public String getScopeStr() {
        return this.scopeStr;
    }

    public void setScopeStr(String scopeStr) {
        this.scopeStr = scopeStr;
    }

    public String getMcaHabilitado() {
        return this.mcaHabilitado;
    }

    public void setMcaHabilitado(String mcaHabilitado) {
        this.mcaHabilitado = mcaHabilitado;
    }

    public Date getFecActu() {
        return this.fecActu;
    }

    public void setFecActu(Date fecActu) {
        this.fecActu = fecActu;
    }

    public String getIdUsuarioModif() {
        return this.idUsuarioModif;
    }

    public void setIdUsuarioModif(String idUsuarioModif) {
        this.idUsuarioModif = idUsuarioModif;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Clientes (");

        sb.append(idCliente);
        sb.append(", ").append(accessTokenValiditySecondsAlias);
        sb.append(", ").append(additionalInformationStr);
        sb.append(", ").append(authoritiesStr);
        sb.append(", ").append(authorizedGrantTypeStr);
        sb.append(", ").append(clientIdAlias);
        sb.append(", ").append(clientSecretAlias);
        sb.append(", ").append(publicKey);
        sb.append(", ").append(refreshTokenValiditySecondsAlias);
        sb.append(", ").append(registeredRedirectUriStr);
        sb.append(", ").append(resourceIdStr);
        sb.append(", ").append(scopeStr);
        sb.append(", ").append(mcaHabilitado);
        sb.append(", ").append(fecActu);
        sb.append(", ").append(idUsuarioModif);

        sb.append(")");
        return sb.toString();
    }
}
