/*
 * This file is generated by jOOQ.
*/
package com.palominocia.JooqProject.modelo.tables.pojos;


import java.io.Serializable;
import java.sql.Date;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Grupos implements Serializable {

    private static final long serialVersionUID = -1614172969;

    private Long   idGrupo;
    private String nombreGrupo;
    private String mcaHabilitado;
    private Date   fecActu;
    private String idUsuarioModif;

    public Grupos() {}

    public Grupos(Grupos value) {
        this.idGrupo = value.idGrupo;
        this.nombreGrupo = value.nombreGrupo;
        this.mcaHabilitado = value.mcaHabilitado;
        this.fecActu = value.fecActu;
        this.idUsuarioModif = value.idUsuarioModif;
    }

    public Grupos(
        Long   idGrupo,
        String nombreGrupo,
        String mcaHabilitado,
        Date   fecActu,
        String idUsuarioModif
    ) {
        this.idGrupo = idGrupo;
        this.nombreGrupo = nombreGrupo;
        this.mcaHabilitado = mcaHabilitado;
        this.fecActu = fecActu;
        this.idUsuarioModif = idUsuarioModif;
    }

    public Long getIdGrupo() {
        return this.idGrupo;
    }

    public void setIdGrupo(Long idGrupo) {
        this.idGrupo = idGrupo;
    }

    public String getNombreGrupo() {
        return this.nombreGrupo;
    }

    public void setNombreGrupo(String nombreGrupo) {
        this.nombreGrupo = nombreGrupo;
    }

    public String getMcaHabilitado() {
        return this.mcaHabilitado;
    }

    public void setMcaHabilitado(String mcaHabilitado) {
        this.mcaHabilitado = mcaHabilitado;
    }

    public Date getFecActu() {
        return this.fecActu;
    }

    public void setFecActu(Date fecActu) {
        this.fecActu = fecActu;
    }

    public String getIdUsuarioModif() {
        return this.idUsuarioModif;
    }

    public void setIdUsuarioModif(String idUsuarioModif) {
        this.idUsuarioModif = idUsuarioModif;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Grupos (");

        sb.append(idGrupo);
        sb.append(", ").append(nombreGrupo);
        sb.append(", ").append(mcaHabilitado);
        sb.append(", ").append(fecActu);
        sb.append(", ").append(idUsuarioModif);

        sb.append(")");
        return sb.toString();
    }
}
