/*
 * This file is generated by jOOQ.
*/
package com.palominocia.JooqProject.modelo.tables.pojos;


import java.io.Serializable;
import java.sql.Date;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Recursos implements Serializable {

    private static final long serialVersionUID = 1888093060;

    private Long   idRecurso;
    private String nombreRecurso;
    private Long   direccionRecurso;
    private String mcaHabilitado;
    private Date   fecActu;
    private String idUsuarioModif;

    public Recursos() {}

    public Recursos(Recursos value) {
        this.idRecurso = value.idRecurso;
        this.nombreRecurso = value.nombreRecurso;
        this.direccionRecurso = value.direccionRecurso;
        this.mcaHabilitado = value.mcaHabilitado;
        this.fecActu = value.fecActu;
        this.idUsuarioModif = value.idUsuarioModif;
    }

    public Recursos(
        Long   idRecurso,
        String nombreRecurso,
        Long   direccionRecurso,
        String mcaHabilitado,
        Date   fecActu,
        String idUsuarioModif
    ) {
        this.idRecurso = idRecurso;
        this.nombreRecurso = nombreRecurso;
        this.direccionRecurso = direccionRecurso;
        this.mcaHabilitado = mcaHabilitado;
        this.fecActu = fecActu;
        this.idUsuarioModif = idUsuarioModif;
    }

    public Long getIdRecurso() {
        return this.idRecurso;
    }

    public void setIdRecurso(Long idRecurso) {
        this.idRecurso = idRecurso;
    }

    public String getNombreRecurso() {
        return this.nombreRecurso;
    }

    public void setNombreRecurso(String nombreRecurso) {
        this.nombreRecurso = nombreRecurso;
    }

    public Long getDireccionRecurso() {
        return this.direccionRecurso;
    }

    public void setDireccionRecurso(Long direccionRecurso) {
        this.direccionRecurso = direccionRecurso;
    }

    public String getMcaHabilitado() {
        return this.mcaHabilitado;
    }

    public void setMcaHabilitado(String mcaHabilitado) {
        this.mcaHabilitado = mcaHabilitado;
    }

    public Date getFecActu() {
        return this.fecActu;
    }

    public void setFecActu(Date fecActu) {
        this.fecActu = fecActu;
    }

    public String getIdUsuarioModif() {
        return this.idUsuarioModif;
    }

    public void setIdUsuarioModif(String idUsuarioModif) {
        this.idUsuarioModif = idUsuarioModif;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Recursos (");

        sb.append(idRecurso);
        sb.append(", ").append(nombreRecurso);
        sb.append(", ").append(direccionRecurso);
        sb.append(", ").append(mcaHabilitado);
        sb.append(", ").append(fecActu);
        sb.append(", ").append(idUsuarioModif);

        sb.append(")");
        return sb.toString();
    }
}
