/*
 * This file is generated by jOOQ.
*/
package com.palominocia.JooqProject.modelo.tables.pojos;


import java.io.Serializable;
import java.sql.Date;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Roles implements Serializable {

    private static final long serialVersionUID = 1559745241;

    private Long   idRol;
    private String nombreRol;
    private String mcaHabilitado;
    private Date   fecActu;
    private String idUsuarioModif;

    public Roles() {}

    public Roles(Roles value) {
        this.idRol = value.idRol;
        this.nombreRol = value.nombreRol;
        this.mcaHabilitado = value.mcaHabilitado;
        this.fecActu = value.fecActu;
        this.idUsuarioModif = value.idUsuarioModif;
    }

    public Roles(
        Long   idRol,
        String nombreRol,
        String mcaHabilitado,
        Date   fecActu,
        String idUsuarioModif
    ) {
        this.idRol = idRol;
        this.nombreRol = nombreRol;
        this.mcaHabilitado = mcaHabilitado;
        this.fecActu = fecActu;
        this.idUsuarioModif = idUsuarioModif;
    }

    public Long getIdRol() {
        return this.idRol;
    }

    public void setIdRol(Long idRol) {
        this.idRol = idRol;
    }

    public String getNombreRol() {
        return this.nombreRol;
    }

    public void setNombreRol(String nombreRol) {
        this.nombreRol = nombreRol;
    }

    public String getMcaHabilitado() {
        return this.mcaHabilitado;
    }

    public void setMcaHabilitado(String mcaHabilitado) {
        this.mcaHabilitado = mcaHabilitado;
    }

    public Date getFecActu() {
        return this.fecActu;
    }

    public void setFecActu(Date fecActu) {
        this.fecActu = fecActu;
    }

    public String getIdUsuarioModif() {
        return this.idUsuarioModif;
    }

    public void setIdUsuarioModif(String idUsuarioModif) {
        this.idUsuarioModif = idUsuarioModif;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Roles (");

        sb.append(idRol);
        sb.append(", ").append(nombreRol);
        sb.append(", ").append(mcaHabilitado);
        sb.append(", ").append(fecActu);
        sb.append(", ").append(idUsuarioModif);

        sb.append(")");
        return sb.toString();
    }
}
