/*
 * This file is generated by jOOQ.
*/
package com.palominocia.JooqProject.modelo.tables.pojos;


import java.io.Serializable;
import java.sql.Date;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Usuarios implements Serializable {

    private static final long serialVersionUID = -667181049;

    private String idUsuario;
    private String nombre;
    private String password;
    private String descripcion;
    private String mcaHabilitado;
    private Date   fecActu;
    private String idUsuarioModif;

    public Usuarios() {}

    public Usuarios(Usuarios value) {
        this.idUsuario = value.idUsuario;
        this.nombre = value.nombre;
        this.password = value.password;
        this.descripcion = value.descripcion;
        this.mcaHabilitado = value.mcaHabilitado;
        this.fecActu = value.fecActu;
        this.idUsuarioModif = value.idUsuarioModif;
    }

    public Usuarios(
        String idUsuario,
        String nombre,
        String password,
        String descripcion,
        String mcaHabilitado,
        Date   fecActu,
        String idUsuarioModif
    ) {
        this.idUsuario = idUsuario;
        this.nombre = nombre;
        this.password = password;
        this.descripcion = descripcion;
        this.mcaHabilitado = mcaHabilitado;
        this.fecActu = fecActu;
        this.idUsuarioModif = idUsuarioModif;
    }

    public String getIdUsuario() {
        return this.idUsuario;
    }

    public void setIdUsuario(String idUsuario) {
        this.idUsuario = idUsuario;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public String getMcaHabilitado() {
        return this.mcaHabilitado;
    }

    public void setMcaHabilitado(String mcaHabilitado) {
        this.mcaHabilitado = mcaHabilitado;
    }

    public Date getFecActu() {
        return this.fecActu;
    }

    public void setFecActu(Date fecActu) {
        this.fecActu = fecActu;
    }

    public String getIdUsuarioModif() {
        return this.idUsuarioModif;
    }

    public void setIdUsuarioModif(String idUsuarioModif) {
        this.idUsuarioModif = idUsuarioModif;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Usuarios (");

        sb.append(idUsuario);
        sb.append(", ").append(nombre);
        sb.append(", ").append(password);
        sb.append(", ").append(descripcion);
        sb.append(", ").append(mcaHabilitado);
        sb.append(", ").append(fecActu);
        sb.append(", ").append(idUsuarioModif);

        sb.append(")");
        return sb.toString();
    }
}
